#!/usr/bin/env python3
from __future__ import annotations
import json, tempfile
from pathlib import Path
from build_linguistic_user_confirmed_gold import ROOT, build, render
GLOB="*-sense-gold.json"
def load(path):
    with path.open(encoding="utf-8") as h:return json.load(h)
def main():
    paths=sorted((ROOT/"data/linguistic/gold").glob(GLOB)); discovered=0
    for path in paths:
        gold=load(path); provenance=gold.get("provenance",{})
        if provenance.get("validationType")!="user-confirmed": continue
        discovered+=1
        source=provenance.get("sourceReview"); review_mission=provenance.get("reviewMission"); confirmation_mission=provenance.get("confirmationMission")
        assert isinstance(source,str) and source; assert isinstance(review_mission,str) and review_mission; assert isinstance(confirmation_mission,str) and confirmation_mission
        rebuilt=render(build(ROOT/source,review_mission,confirmation_mission))
        assert rebuilt==path.read_bytes(),f"{path}: regenerated bytes differ"
    assert discovered>0,"no user-confirmed semantic gold found"
    print(f"PASS userConfirmedGolds={discovered}")
if __name__=="__main__": main()
