#!/usr/bin/env python3
"""First close semantic pass for Gabriel book 22, Psalms 138-141, PDF-derived only."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; PATH=ROOT/'data/thematic-index/books/book-22.json'
def T(i,l,imp,d,v,t): return {'themeId':i,'label':l,'importance':imp,'directness':d,'verseNumbers':v,'teaching':t}
DEEP={
138:{'signals':['digestion','assimilation','individualisation','expérience','nourriture'], 'themes':[
 T('digestion-de-l-experience','Digestion de l’expérience','central','symbolic',[7,8,9,10,11,12,14,17,19,24,25,26,27,28,29],"La digestion sert de modèle pour transformer une expérience en compréhension et en corps. L’homme doit goûter, expérimenter, observer les effets puis assimiler ce qui est juste au lieu de répéter mécaniquement des comportements qu’il n’a jamais réellement compris."),
 T('individualisation','Individualisation','central','direct',[5,6,7,9,10,11,17,18,19,20,21,24,25],"L’individualisation commence lorsque l’homme sort de l’imitation et vérifie par lui-même ce qu’il reçoit. Étudier signifie alors éveiller une lumière intérieure, discerner, expérimenter et devenir responsable de la part singulière qu’il apporte au Bien commun."),
 T('etude-comme-assimilation','Étude comme assimilation','central','symbolic',[10,11,12,14,17,24,25,29],"L’étude n’est pas présentée comme acquisition extérieure d’informations mais comme assimilation d’une nourriture. Une sagesse étudiée, digérée et vécue doit s’ancrer dans l’être jusqu’à former un corps capable de continuer à agir dans plusieurs mondes."),
 T('nourriture-et-destinee','Nourriture et destinée','important','symbolic',[8,26,27,28,29],"Chaque nourriture est reliée à un devenir : ce que l’homme laisse entrer dans sa pensée, ses sentiments et sa vie contribue à former le corps et la destination auxquels il s’accorde. Le choix de la nourriture dépend donc de ce qu’il veut réellement devenir."),
 T('bien-commun-universel','Bien commun universel','important','direct',[1,2,3,10,14,15,16,20,21,22],"Une expérience correctement assimilée doit dépasser le bénéfice personnel. Le psaume demande d’unir le petit au grand et d’évaluer les actes selon leur contribution à l’humanité, aux règnes visibles et invisibles et à une harmonie plus vaste."),
 T('discernement-contre-imitation','Discernement contre imitation','important','direct',[5,6,7,9,17,18,25,26,27],"L’imitation peut servir au début de l’apprentissage mais devient enfermante si elle remplace l’expérience. Le discernement exige de goûter, vérifier et mesurer les conséquences avant d’adopter une pratique ou une opinion comme vraie."),
]},
139:{'signals':['temple intérieur','eau aurique','influences','maîtrise','corps'], 'themes':[
 T('eau-aurique-et-influences','Eau aurique et influences','central','symbolic',[3,4,5,6,7,8,10,14,17,19],"Le psaume décrit autour de l’homme une eau aurique où pensées, sentiments et volontés nourrissent des mondes qui exercent à leur tour une influence. Prendre conscience de ce milieu est présenté comme une condition pour ne plus confondre liberté personnelle et impulsions reçues."),
 T('maitrise-de-la-destinee','Maîtrise de la destinée','central','direct',[1,2,4,7,10,11,12,13,14,16,17,18,19,21,22],"La maîtrise ne vient pas du simple vouloir mais de la récupération consciente de ses instruments. Étude, discipline et formation d’un corps doivent rendre l’homme moins dépendant des humeurs, atmosphères et influences et plus capable de conduire sa vie selon une orientation choisie."),
 T('temple-interieur','Temple intérieur','central','symbolic',[11,12,13,20,21,22,23,24,26,27,28],"Construire le temple intérieur signifie former un corps stable par l’étude, la dévotion, le rite et l’œuvre. Ce temple doit ensuite s’élargir au cercle d’étude, où la maîtrise individuelle devient soutien collectif et continuité de l’œuvre."),
 T('corps-de-conscience','Corps de conscience','important','direct',[11,13,14,16,18,22,23,24,26,27],"Le corps de conscience désigne une maîtrise devenue constante plutôt qu’occasionnelle. Il se forme lorsque les organes, facultés et actes deviennent des alliés suffisamment stables pour porter ce que l’homme reconnaît comme juste."),
 T('discernement-des-presences','Discernement des présences','important','direct',[3,4,5,7,8,10,14,17,19],"Le texte demande d’identifier les mondes qui utilisent pensée, sentiment et volonté comme points d’entrée. Le discernement sert à ne pas parler ou agir sous n’importe quelle influence et à orienter consciemment ce qui reçoit de la force."),
 T('constance-et-aboutissement','Constance et aboutissement','important','direct',[12,13,16,25,27,28],"La fidélité à ce qui est reconnu comme juste doit aller jusqu’à l’aboutissement. Commencer plusieurs choses sans les conduire à terme entretient la confusion, tandis qu’un pas achevé devient une base pour le suivant."),
]},
140:{'signals':['servitude','service','corps','fructification','équilibre des mondes'], 'themes':[
 T('servitude-invisible','Servitude invisible','central','direct',[1,2,4,6,7,8,9,14,19],"Le psaume oppose la prétention humaine à la maîtrise à une servitude envers des intelligences invisibles qui récupèrent les forces détournées du monde divin. L’homme peut croire travailler pour lui tout en servant un monde dont il ignore la finalité."),
 T('service-du-monde-divin','Service du monde divin','central','direct',[3,10,11,12,13,15,16,17,18,20,21,23],"Le service juste est présenté comme un échange où l’homme reçoit une semence, lui donne un corps et la fait fructifier pour l’universel. La finalité n’est pas l’autoglorification mais la capacité d’accomplir une volonté supérieure sans la déformer selon ses intérêts."),
 T('corps-de-l-enseignement','Corps de l’Enseignement','central','direct',[11,16,18,20,22,23],"L’étude, la dévotion, le rite et l’œuvre doivent constituer un corps adapté à ce qui veut être reçu. Sans structure et organes capables de porter une semence jusqu’au fruit, une aspiration lumineuse reste sans manifestation réelle."),
 T('equilibre-visible-invisible','Équilibre visible-invisible','important','direct',[2,3,5,6,14,22],"Le texte critique l’usage de toute l’intelligence pour renforcer uniquement le monde matériel. Comme l’arbre qui ne se réduit pas à son fruit, la vie doit conserver une relation entre visible, invisible et source plutôt que concentrer toutes les forces dans une seule dimension."),
 T('fructification','Fructification','important','symbolic',[10,18,20,22,23],"Ce qui est reçu doit être planté, développé et rendu plus riche. La fructification sert de critère à la capacité du serviteur : bien utiliser une petite force ouvre la possibilité d’en recevoir davantage, tandis que l’accaparement ferme le circuit."),
 T('impersonnalite','Impersonnalité','important','direct',[10,16,18,20,23],"L’impersonnalité est la disposition qui permet d’approcher une volonté supérieure sans la ramener au désir de sauver, enrichir ou glorifier l’individu. Elle rend possible une œuvre orientée vers l’Alliance et le Bien commun."),
]},
141:{'signals':['Tradition vivante','mémoire','transmission','semence','générations futures'], 'themes':[
 T('tradition-vivante','Tradition vivante','central','direct',[1,2,3,4,6,10,11,12,13,14,16,17,18,20,21,24,25,26,27,28],"La Tradition est décrite comme la mémoire et l’âme qui traversent les générations. Elle reste vivante lorsque ce qui est reçu est cultivé, approfondi et redonné sous une forme capable de nourrir les suivants plutôt que dilapidé dans le présent."),
 T('transmission-des-valeurs','Transmission des valeurs','central','direct',[2,3,5,6,7,8,9,10,11,13,15,16,17,21,23,24,25,27],"La transmission porte sur des valeurs, des savoir-faire et une manière d’habiter les activités avec une âme et un sens. La rupture de cette chaîne est présentée comme une perte de fondements qui prive les générations futures d’un langage pour leur vie intérieure."),
 T('semence-et-terre','Semence et terre','central','symbolic',[3,13,17,18,19,20,21,23,24,27],"La mémoire est comparée à une semence qui doit rencontrer une terre travaillée, puis l’eau, l’air et le feu nécessaires à sa croissance. Le travail individuel prépare cette terre et le cercle d’étude propage les semences autour de lui."),
 T('memoire-des-origines','Mémoire des origines','important','direct',[2,4,11,12,13,14,17,18,20,24,25],"L’homme doit se souvenir d’où il vient, de sa mission et de ce qu’il a à transmettre. L’étude et la méditation servent à réactiver une résonance devenue faible lorsque les familles, métiers et cultures ne portent plus la même mémoire."),
 T('responsabilite-envers-les-generations','Responsabilité envers les générations','important','direct',[5,6,8,9,13,15,16,17,21,23,24,27],"Recevoir un héritage crée une responsabilité envers ceux qui viennent après. La valeur d’une tradition se mesure à sa capacité de faire croître le Bien commun au fil des générations, non à conserver passivement des formes anciennes."),
 T('corps-d-immortalite','Corps d’immortalité','important','direct',[18,20,21,22,24,27],"Le travail individuel de l’étude, de la dévotion, du rite et de l’œuvre est explicitement relié à la création d’un corps d’immortalité. La continuité recherchée passe par une pratique et une transmission actives plutôt que par le souvenir seul."),
]}}
def merge(e,n):
 by={t.get('themeId'):t for t in e}; [by.__setitem__(t['themeId'],t) for t in n]; o={t['themeId']:i for i,t in enumerate(n)}
 return sorted(by.values(),key=lambda t:(0 if t.get('themeId') in o else 1,o.get(t.get('themeId'),999),t.get('themeId','')))
def main():
 d=json.loads(PATH.read_text(encoding='utf-8')); by={a['number']:a for a in d['psalmAnalyses']}
 for num,s in DEEP.items(): by[num].update({'titleSignals':s['signals'],'themes':merge(by[num].get('themes',[]),s['themes']),'semanticDepth':'deep-content-grounded'})
 d['psalmAnalyses']=sorted(by.values(),key=lambda a:a['number']); m=d.setdefault('method',{}); m['semanticPass']='deepening-in-progress'; m['deepPsalmCount']=sum(a.get('semanticDepth')=='deep-content-grounded' for a in d['psalmAnalyses']); PATH.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n',encoding='utf-8'); print(f"Book 22 deep total={m['deepPsalmCount']}")
if __name__=='__main__': main()
