#!/usr/bin/env python3
"""Seventh close semantic pass for Michael book 21, Psalms 155-159, PDF-derived only."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; PATH=ROOT/'data/thematic-index/books/book-21.json'
def T(i,l,imp,d,v,t): return {'themeId':i,'label':l,'importance':imp,'directness':d,'verseNumbers':v,'teaching':t}
DEEP={
155:{'signals':['quatre corps','corps physique','résonance','étude de soi','présence divine'], 'themes':[
 T('corps-comme-cle','Corps comme clé','central','direct',[1,2,3,4,5,8,15,16,17,19,20,21,22,23,25,26,27,28],"Le corps physique est présenté comme la clé permettant d’étudier les autres dimensions de l’homme. Plutôt que d’abstraire les corps subtils, le texte demande d’observer les réactions, rythmes et fonctions concrètes du corps afin d’en comprendre les correspondances."),
 T('quatre-corps','Quatre corps','central','direct',[5,6,7,9,10,11,12,13,15,19],"Le psaume distingue des corps d’air, d’eau, de terre et de feu et propose pour chacun une voie d’observation corporelle : atmosphères et respiration, relations et impressions, soin du corps physique, regard et sommeil. La connaissance passe par l’expérience plutôt que par une théorie seule."),
 T('corps-revelateur','Corps révélateur','central','direct',[6,7,8,9,10,11,12,13,21,22],"Le corps est décrit comme une sonde qui révèle la qualité des échanges et des mondes présents. L’écouter permet de lire les effets d’une atmosphère, d’une relation, d’une nourriture, d’un regard ou d’un rythme sur l’ensemble de l’être."),
 T('etude-de-soi','Étude de soi','important','direct',[8,10,11,13,19,20,21,22],"Avant de prétendre connaître les autres ou les mondes supérieurs, l’homme doit apprendre à se connaître et à se maîtriser. Cette étude progressive développe une sensibilité aux lois et aux relations qui traversent son propre organisme."),
 T('corps-comme-instrument-d-unification','Corps comme instrument d’unification','important','direct',[3,4,16,17,18,19,22,28],"Le corps est un instrument prêté pour une œuvre et orienté vers l’unification de ses fonctions. Sa sagesse apparaît lorsque les organes coopèrent et que les différents corps peuvent être éduqués pour servir une même vie plutôt que se désorganiser."),
 T('presence-divine-dans-le-corps','Présence divine dans le corps','important','direct',[15,16,17,23,24,25,26,27,28],"Le texte affirme que la présence du monde divin doit être cherchée dans ce qui est, et particulièrement dans le corps, plutôt que dans des abstractions. Le corps devient ainsi le point concret où une intelligence supérieure peut être reconnue et servie."),
]},
156:{'signals':['écritures durables','accomplissement','conscience','corps collectif','concentration'], 'themes':[
 T('ecritures-durables','Écritures durables','central','symbolic',[1,2,3,4,5,7,9,18,24,26,27,28],"Les œuvres sont présentées comme des écritures capables de durer lorsqu’elles reçoivent un corps, une identité et un accomplissement complet. Le but n’est pas d’accumuler un savoir mais de laisser une réalité suffisamment constituée pour traverser le temps."),
 T('accomplissement','Accomplissement','central','direct',[3,7,10,11,15,16,18,26,27,28,30,31],"L’accomplissement demande de conduire une chose jusqu’au bout plutôt que de multiplier les activités. Une œuvre achevée peut s’unir à l’ensemble et devenir un élément solide du corps collectif, alors que la dispersion affaiblit tout."),
 T('conscience-dans-l-oeuvre','Conscience dans l’œuvre','central','direct',[1,2,8,12,13,14,16,17,23],"La conscience doit précéder et accompagner l’action. Les œuvres motivées seulement par la peur, le désir de plaire ou le besoin d’exister sont distinguées d’un travail posé dans la clarté, l’intelligence et la présence à ce qui est réellement construit."),
 T('corps-collectif','Corps collectif','important','direct',[5,8,9,11,17,18,19,29,30,31,32],"La Nation est envisagée comme un corps que les œuvres individuelles doivent fortifier. La coopération, la réconciliation et la capacité de chaque monde à trouver une place sont nécessaires pour qu’une tradition collective grandisse au lieu de s’éteindre."),
 T('concentration','Concentration','important','direct',[10,11,15,18,28],"La concentration est l’antidote à la multiplication des activités sans résultat. Le texte demande de prendre une œuvre à la fois et de la conduire à la perfection de sa réalisation avant de disperser les forces ailleurs."),
 T('argent-comme-energie-de-croissance','Argent comme énergie de croissance','important','direct',[20,21,22],"L’argent est présenté comme une énergie qui doit circuler, fructifier et faire grandir la communauté plutôt que devenir force d’enfermement ou d’accumulation. Sa juste place est intégrée au travail plus large de construction d’un corps collectif."),
]},
157:{'signals':['sagesse éternelle','lois','discernement','étude','mise en pratique'], 'themes':[
 T('sagesse-eternelle','Sagesse éternelle','central','direct',[1,2,3,4,5,6,7,8,9,10,16,17,19,20,22,34,38,39],"La sagesse est présentée comme une réalité antérieure aux constructions humaines et comme la source des lois qui ordonnent la vie. Elle n’est pourtant pas lointaine : le texte demande de l’étudier, de vivre avec elle et de la faire passer dans toutes les activités."),
 T('corps-de-la-sagesse','Corps de la sagesse','central','direct',[4,5,8,11,12,13,14,28,30,33,35,37,38,39],"L’enseignement doit former un corps dans lequel la sagesse puisse s’incarner. Étude, dévotion, rites et œuvres rendent progressivement cette sagesse opérante dans le quotidien au lieu de la laisser comme idéal abstrait."),
 T('discernement-et-verification','Discernement et vérification','central','direct',[15,21,22,25,26,27,29,30,35,36,40,41],"Le psaume refuse la croyance aveugle dans ceux qui paraissent sages. Il demande de vérifier, comprendre et appliquer ce qui est enseigné, puis d’évaluer les fruits afin de distinguer ce qui fonctionne et ouvre la vie de ce qui entretient l’illusion."),
 T('sagesse-comme-bien-commun','Sagesse comme Bien commun','important','direct',[6,9,10,22,23,24,28,33,35],"L’intelligence et la sagesse ne sont pas réservées à une élite. Elles sont décrites comme un bien commun qui doit élever le peuple, les œuvres et les générations futures, de sorte qu’un guide véritable rend également son entourage plus capable."),
 T('mise-en-pratique','Mise en pratique','important','direct',[13,14,16,17,26,28,29,30,32,33,35,37,39],"La sagesse se reconnaît à ce qui peut être vécu et expérimenté chaque jour. L’homme doit choisir progressivement les voies qui donnent des résultats cohérents et abandonner celles qui ne font qu’entretenir habitudes et esclavages."),
 T('oeuvre-et-heritage','Œuvre et héritage','important','direct',[8,14,23,28,33,35],"Le passage terrestre est évalué par ce qui est vécu et laissé comme œuvre ou message. Une sagesse incarnée devient un héritage qui éclaire d’autres êtres, tandis qu’un savoir non vécu ne dépasse pas celui qui l’a accumulé."),
]},
158:{'signals':['mission','mémoire','sens de la vie','fidélité','préparation'], 'themes':[
 T('memoire-de-la-mission','Mémoire de la mission','central','direct',[1,2,5,7,8,9,10,11,13,19,24],"La mémoire essentielle est celle du pourquoi de la présence sur terre, de l’œuvre à accomplir et des associations nécessaires pour la réaliser. Le texte demande de la réveiller tôt et de la cultiver tout au long de la vie plutôt que d’attendre la proximité de la mort."),
 T('vie-terrestre-comme-moyen','Vie terrestre comme moyen','central','direct',[3,4,5,9,10,11,12,13,17,19,20,21,22,23],"La vie matérielle est nécessaire mais n’est pas présentée comme une fin en soi. Elle fournit les conditions où une mission doit être recherchée et réalisée, en gardant assez d’espace pour entendre les signes et la mémoire qui orientent au-delà de la seule survie."),
 T('fidelite-a-sa-destinee','Fidélité à sa destinée','central','direct',[2,9,11,13,19,20,21,22,23,24],"Rester fidèle signifie ne pas abandonner les valeurs et l’orientation profondes sous la pression des nécessités matérielles. Le texte associe cette fidélité à la possibilité de conserver une continuité de conscience et d’obtenir les conditions nécessaires à l’œuvre."),
 T('epreuve-comme-eveil','Épreuve comme éveil','important','direct',[13,14,15,16,19,20],"L’épreuve et le malheur ne sont pas toujours interprétés comme fatalité. Ils peuvent forcer une remise en mouvement et aider l’homme à devenir plus clair et plus fort, à condition qu’il ne s’enferme pas dans une identité de victime du destin."),
 T('tradition-et-memoriaux','Tradition et mémoriaux','important','direct',[17,18,19,24],"La Tradition sert à réactiver et protéger la mémoire d’un chemin plus vaste. Les mémoriaux sont proposés comme structures permettant de garder vivantes ces orientations pour soi et pour les générations futures."),
 T('preparation-a-l-apres-vie','Préparation à l’après-vie','important','direct',[5,6,7,16,17,19,23,24],"La vie est également décrite comme préparation à ce qui suit la mort. Ce qui est cultivé dans la mémoire, les valeurs et les œuvres doit former une continuité plutôt que laisser l’homme entièrement identifié à l’éphémère."),
]},
159:{'signals':['religion vivante','lien','jardin d’Éden','Père et Mère','communauté'], 'themes':[
 T('religion-comme-lien','Religion comme lien','central','direct',[1,2,3,4,5,6,7,8,10,17,18],"La Religion est définie comme l’acte de relier les régions, les mondes et les êtres dans une unité vivante, non comme une croyance particulière. Le lien de Lumière doit circuler entre ciel et terre et faire de l’homme un intermédiaire plutôt qu’un être séparé."),
 T('homme-trait-d-union','Homme trait d’union','central','direct',[7,8,10,11,14,15,17,18,19,20,21],"La destinée de l’homme est de tenir ensemble le haut et le bas, le Père et la Mère, le corps et l’esprit. Il devient un temple vivant lorsqu’il peut recevoir une intelligence supérieure puis la conduire jusque dans la vie terrestre et les règnes."),
 T('jardin-d-eden','Jardin d’Éden','central','symbolic',[19,20,21,22,23,24],"Le jardin d’Éden est présenté comme le lieu intérieur et extérieur où ciel, terre et créatures vivent en harmonie. Le restaurer signifie rétablir d’abord en soi une relation juste entre les mondes puis lui donner un corps sur la terre."),
 T('mere-comme-corps-et-bien-commun','Mère comme corps et Bien commun','important','direct',[11,12,13,14,15,18,22,25],"La Mère porte le corps, la nourriture, la Tradition et les éléments nécessaires à l’incarnation. L’ascension ne doit donc pas devenir fuite de la terre : la sagesse supérieure doit trouver une matière et une famille où devenir visible."),
 T('communaute-comme-corps-de-lumiere','Communauté comme corps de Lumière','important','direct',[25,26,27,28,29],"La communauté fournit le creuset où le corps intérieur peut se nourrir et où une œuvre plus grande devient possible. La Ronde, l’étude, la dévotion, les rites et les œuvres relient les individus sans supprimer leur liberté ni leur rythme propre."),
 T('universalite','Universalité','important','direct',[2,4,6,17,18,23,29],"Le chemin est présenté comme universel parce qu’il doit pouvoir éclairer des religions, cultures et peuples différents sans les réduire à une seule forme. Son critère est la capacité à relier, guérir et conduire vers un accomplissement commun."),
]}}
def merge(e,n):
 by={t.get('themeId'):t for t in e}; [by.__setitem__(t['themeId'],t) for t in n]; o={t['themeId']:i for i,t in enumerate(n)}
 return sorted(by.values(),key=lambda t:(0 if t.get('themeId') in o else 1,o.get(t.get('themeId'),999),t.get('themeId','')))
def main():
 d=json.loads(PATH.read_text(encoding='utf-8')); by={a['number']:a for a in d['psalmAnalyses']}
 for num,s in DEEP.items(): by[num].update({'titleSignals':s['signals'],'themes':merge(by[num].get('themes',[]),s['themes']),'semanticDepth':'deep-content-grounded'})
 d['psalmAnalyses']=sorted(by.values(),key=lambda a:a['number']); m=d.setdefault('method',{}); m['semanticPass']='deepening-in-progress'; m['deepPsalmCount']=sum(a.get('semanticDepth')=='deep-content-grounded' for a in d['psalmAnalyses']); PATH.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n',encoding='utf-8'); print(f"Book 21 deep total={m['deepPsalmCount']}")
if __name__=='__main__': main()
