#!/usr/bin/env python3
"""Final close semantic pass for Michael book 21, Psalms 160-164, PDF-derived only."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; PATH=ROOT/'data/thematic-index/books/book-21.json'
def T(i,l,imp,d,v,t): return {'themeId':i,'label':l,'importance':imp,'directness':d,'verseNumbers':v,'teaching':t}
DEEP={
160:{'signals':['concentration','présence','opportunité','méditation','réalisation'], 'themes':[
 T('concentration','Concentration','central','direct',[1,2,3,5,8,9,10,15,16,17,18,19,20,23,24,25,26],"La concentration est définie comme la capacité de rester présent, clair et suffisamment stable pour percevoir les influences, lire les réponses et saisir le moment où une possibilité peut être transformée en réalisation. Elle s’oppose à la dispersion et à la passivité."),
 T('presence-d-esprit','Présence d’esprit','central','direct',[2,3,5,8,9,16,17,19,20],"La présence d’esprit permet de demeurer dans ce qui est plutôt que dans le rêve ou l’anticipation. Elle rend l’homme disponible au moment précis où une pièce du processus apparaît et lui évite de subir automatiquement les courants environnants."),
 T('realisation-pas-a-pas','Réalisation pas à pas','central','direct',[5,10,16,17,18,19,24,25,26],"La réalisation est comparée à un puzzle et à un chemin parcouru étape par étape. Il faut reconnaître, choisir et placer chaque élément à sa juste place jusqu’à ce que l’œuvre forme un corps vivant et autonome."),
 T('meditation-comme-art-de-vivre','Méditation comme art de vivre','important','direct',[3,8,15,16,19],"La méditation est présentée comme une culture permanente de l’attention, de la clarté et de la vie intérieure, non comme une activité isolée. Elle entraîne la vigilance nécessaire pour recevoir et utiliser les occasions qui se présentent."),
 T('tradition-comme-terre-de-concentration','Tradition comme terre de concentration','important','symbolic',[20,21,22,23,24,25,26,27,28],"La Tradition fournit une terre, un horizon et un but qui rendent la concentration possible. Elle situe chaque étape particulière dans un projet plus vaste afin que l’homme sache qui il est, à quoi il se relie et où il veut conduire sa vie."),
 T('ecoute-de-la-reponse','Écoute de la réponse','important','direct',[7,8,9,10,11,18],"Demander sans écouter entretient l’instabilité. Le texte insiste sur la patience et l’attention au retour : une réponse peut prendre une forme différente de celle imaginée et doit être reconnue à partir de ce que l’homme est réellement capable de porter."),
]},
161:{'signals':['fin de cycle','choix','futur','individualisation','corps de l’Alliance'], 'themes':[
 T('futur-ecrit-dans-le-present','Futur écrit dans le présent','central','direct',[1,2,3,4,5,8,9,16,17,23,24,25],"Dans la logique prophétique du psaume, le futur se constitue à partir de ce qui est effectivement vécu et construit maintenant. Les désirs déclarés ne suffisent pas : ce sont les associations, les actes, les œuvres et les corps formés qui déterminent le monde auquel l’homme se relie."),
 T('choix-et-individualisation','Choix et individualisation','central','direct',[2,3,4,5,7,8,11,12,13,17],"Le texte oppose la passivité d’une destinée collective subie à l’individualisation par un choix conscient. S’individualiser signifie se créer un corps, identifier les influences qui ont réellement gouverné la vie et prendre activement une autre orientation."),
 T('corps-de-l-alliance','Corps de l’Alliance','central','direct',[2,5,8,10,13,15,18,20,22,25],"Le corps de l’Alliance est présenté comme le support capable de maintenir une possibilité d’évolution et de transmission. Il doit être construit par des œuvres, des structures et une participation concrète plutôt que seulement par adhésion intérieure."),
 T('nettoyage-des-liens','Nettoyage des liens','important','direct',[4,7,11,12,13],"Avant le passage décrit par le texte, l’homme est invité à reconnaître et alléger les liens avec les ancêtres, les égrégores et l’éphémère qui limitent sa liberté. Ce nettoyage doit rendre le choix plus clair et la destinée moins dépendante des appartenances inconscientes."),
 T('semence-d-une-autre-humanite','Semence d’une autre humanité','important','contextual',[14,15,16,20,21,22,23,25],"Le psaume expose une vision prophétique de deux orientations d’humanité et présente la Nation comme semence d’une autre civilisation. Cette relation est indexée comme contenu interne du texte, sans transformer cette prophétie en affirmation factuelle sur l’avenir."),
 T('responsabilite-creatrice','Responsabilité créatrice','important','direct',[5,8,16,17,18,20,23,24,25],"L’homme est appelé à ne pas abandonner sa force créatrice à la prise en charge ou au laisser-aller. Chaque jour doit apporter un acte qui donne un corps au futur choisi et maintient un chemin accessible pour d’autres êtres."),
]},
162:{'signals':['dignité des règnes','Mère','intermédiaire','espace sacré','Bien commun'], 'themes':[
 T('dignite-des-regnes','Dignité des règnes','central','direct',[1,2,3,4,5,6,8,9,10,11,12,13,14,17,18,19,20,22,24,25,26,27,28,29],"Le psaume demande de restaurer la dignité propre des minéraux, végétaux et animaux au lieu de les réduire à des ressources. Chaque règne est présenté comme porteur d’une intelligence et d’une place qui doivent être reconnues dans les décisions humaines."),
 T('homme-intermediaire','Homme intermédiaire','central','direct',[1,2,3,5,14,18,19,26,27,28],"L’homme retrouve sa noblesse lorsqu’il exerce sa fonction d’intermédiaire entre le Père et la Mère au service de tous les règnes. Sa position ne lui donne pas un droit de domination mais une responsabilité de relation, de consultation et de libération."),
 T('espace-sacre-pour-les-regnes','Espace sacré pour les règnes','central','direct',[3,4,8,9,13,15,16,20,21,23,29],"Le texte demande d’ouvrir des espaces physiques, collectifs et intérieurs où les règnes puissent être intégrés au chemin. La Ronde, les villages, les cercles d’étude et la conscience personnelle sont décrits comme différents niveaux d’un même espace d’accueil."),
 T('bien-commun-des-regnes','Bien commun des règnes','important','direct',[3,4,5,7,8,13,15,18,20,27,28],"Le Bien commun inclut explicitement les autres règnes. Les œuvres humaines doivent donc être évaluées selon leur capacité à ouvrir une possibilité de vie, d’évolution et de relation plutôt qu’à augmenter l’exploitation et l’enfermement."),
 T('gratitude-envers-la-mere','Gratitude envers la Mère','important','direct',[6,7,10,17,18,24,25],"L’intégration commence par la gratitude envers les règnes pour ce qu’ils apportent à l’existence humaine : stabilité, force vitale, sens, équilibre et enseignement. Cette reconnaissance doit modifier le langage et le comportement envers eux."),
 T('alliance-des-sept-regnes','Alliance des sept règnes','important','direct',[25,26,27,28,29],"La volonté du Père est décrite comme se manifestant à travers l’alliance des règnes plutôt que par le seul homme. Penser collectivement dans cette alliance doit restaurer une intelligence plus complète où l’humanité redevient une partie de l’ensemble."),
]},
163:{'signals':['guidance','harmonie','hiérarchie','vie collective','conseil de sages'], 'themes':[
 T('guidance-d-un-monde-superieur','Guidance d’un monde supérieur','central','direct',[2,3,4,5,6,15,16,18,19,23,24,25],"Le psaume demande de ne pas commencer une œuvre depuis la seule volonté individuelle mais de la confronter à un ordre plus vaste, à l’Enseignement et à l’Alliance. La guidance est ainsi associée à une consultation et à une mise en conformité plutôt qu’à une inspiration privée incontrôlée."),
 T('harmonie-avant-l-oeuvre','Harmonie avant l’œuvre','central','direct',[2,3,5,6,9,10,15,22,27,29,30,35,36],"L’harmonie est présentée comme une condition préalable à la réalisation. Si l’œuvre naît dans le désaccord des mondes ou des personnes, les oppositions apparaissent ensuite comme signe qu’une relation n’a pas été suffisamment intégrée."),
 T('vie-collective','Vie collective','central','direct',[7,8,11,12,13,14,17,23,26,27,28,29,30,31,32,33,34,35,36],"La vie individuelle ne suffit pas : l’homme appartient à des ensembles dont les orientations influencent sa destinée. Le texte demande donc de rendre consciente la vie collective et de construire des institutions capables de porter une intelligence commune claire."),
 T('hierarchie-et-appartenance','Hiérarchie et appartenance','important','direct',[7,8,9,20,21,23,24,34],"La hiérarchie désigne les mondes, responsables et intelligences auxquels l’individu est relié. La question décisive devient : avec qui et avec quoi l’homme est-il réellement associé, puisque son appartenance collective participe au sens de ses actes."),
 T('conseil-de-sages','Conseil de sages','important','direct',[3,5,12,14,26,27,28,29,30,31,34,36],"Le conseil de sages est proposé comme organe de gouvernement chargé de préserver l’accord avec l’Alliance. Son autorité dépend de la clarté, de l’unité entre pensée, sentiment et action et de la mise en pratique de l’Enseignement."),
 T('clarification-des-desaccords','Clarification des désaccords','important','direct',[27,28,29,30,32,35,36],"Les désaccords ne doivent pas être masqués. Ils appellent discipline, travail sur soi et réajustement afin que l’institution ne devienne pas un mélange de mondes contradictoires qui affaiblit ceux qu’elle prétend guider."),
]},
164:{'signals':['pionniers','écriture','fidélité','union','ancrage'], 'themes':[
 T('pionniers','Pionniers','central','direct',[1,2,3,4,6,7,8,10,14,15,17,20],"Le pionnier est celui qui répond à un appel et pose le premier une œuvre dont d’autres pourront bénéficier. La valeur de cette action ne réside pas seulement dans l’événement initial mais dans la fidélité nécessaire pour continuer le chemin ouvert et le rendre durable."),
 T('ecriture-sur-la-terre','Écriture sur la terre','central','symbolic',[1,2,3,4,7,11,20],"La participation collective est décrite comme une écriture déposée dans plusieurs mondes puis destinée à recevoir un ancrage terrestre. Cette écriture doit devenir structure, enseignement et corps plutôt que rester un moment isolé."),
 T('union-et-force-collective','Union et force collective','central','direct',[9,10,12,13,15,16,17,18,19],"L’union transforme la présence de plusieurs personnes en un corps capable de porter une œuvre. Les discordes et malentendus sont présentés comme des faiblesses structurelles qu’il faut clarifier avant qu’elles ne fragilisent durablement ce corps."),
 T('fidelite-a-l-acte','Fidélité à l’acte','important','direct',[1,4,6,7,9,11,17,18,19,20],"Le texte demande d’aller jusqu’au bout de l’acte commencé. La fidélité permet à un premier engagement de devenir un capital, une structure et une continuité au lieu de s’éteindre après l’impulsion initiale."),
 T('ancrage-des-quatre-archanges','Ancrage des quatre Archanges','important','contextual',[9,11,18,19],"Dans le contexte particulier d’Haïti décrit par le psaume, les quatre célébrations sont présentées comme un moyen d’ancrer la Ronde et de maintenir un lien permanent. Cette relation décrit le dispositif interne du texte sans en faire une affirmation extérieure vérifiée."),
 T('formation-et-transmission','Formation et transmission','important','direct',[10,14,17,19,20,21],"La pérennité de l’œuvre suppose que les participants se forment, apprennent et puissent ensuite ouvrir le chemin à d’autres chercheurs. L’ancrage matériel et la transmission de la parole donnent une suite collective à l’expérience initiale."),
]}}
def merge(e,n):
 by={t.get('themeId'):t for t in e}; [by.__setitem__(t['themeId'],t) for t in n]; o={t['themeId']:i for i,t in enumerate(n)}
 return sorted(by.values(),key=lambda t:(0 if t.get('themeId') in o else 1,o.get(t.get('themeId'),999),t.get('themeId','')))
def main():
 d=json.loads(PATH.read_text(encoding='utf-8')); by={a['number']:a for a in d['psalmAnalyses']}
 for num,s in DEEP.items(): by[num].update({'titleSignals':s['signals'],'themes':merge(by[num].get('themes',[]),s['themes']),'semanticDepth':'deep-content-grounded'})
 d['psalmAnalyses']=sorted(by.values(),key=lambda a:a['number']); m=d.setdefault('method',{}); m['semanticPass']='deepening-in-progress'; m['deepPsalmCount']=sum(a.get('semanticDepth')=='deep-content-grounded' for a in d['psalmAnalyses']); PATH.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n',encoding='utf-8'); print(f"Book 21 deep total={m['deepPsalmCount']}")
if __name__=='__main__': main()
