#!/usr/bin/env python3
"""Second close semantic pass for Michael book 21, Psalms 136-139, PDF-derived only."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; PATH=ROOT/'data/thematic-index/books/book-21.json'
def T(i,l,imp,d,v,t): return {'themeId':i,'label':l,'importance':imp,'directness':d,'verseNumbers':v,'teaching':t}
DEEP={
136:{'signals':['trois destinées','pouvoir créateur','Ange','responsabilité','associations'], 'themes':[
 T('trois-destinees','Trois destinées','central','direct',[1,2,6,7,8,9,10,14,17,19,21,26],"Le psaume distingue trois orientations possibles de la destinée — animale, humaine et angélique — en les reliant à des degrés de conscience, de responsabilité et d’association. La maîtrise ne consiste pas à souhaiter un autre futur mais à écrire celui-ci par ce que l’on devient et accomplit."),
 T('maitrise-de-la-destinee','Maîtrise de la destinée','central','direct',[1,2,3,4,5,14,17,19,21,22,23,24,26,31,32],"Maîtriser la destinée signifie reprendre possession de ses facultés, discerner les influences et mettre en action une orientation consciente. Les actes présents sont décrits comme les semences du futur, et non comme des gestes sans conséquence."),
 T('ange-comme-orientation','Ange comme orientation','central','direct',[4,5,7,10,11,12,13,21,23,28,29,30,31,32],"L’Ange est présenté comme un messager qui propose une vertu et une orientation. Il ne remplace pas la responsabilité humaine : l’homme doit entendre, comprendre puis mettre en action ce qui est reçu pour que la relation devienne une destinée vécue."),
 T('responsabilite-individuelle','Responsabilité individuelle','important','direct',[1,14,15,16,17,18,19,22,25,33,34],"L’humanité commence, selon le texte, avec la responsabilité de ses propres pensées, paroles et actes. Juger, fermer un chemin ou semer dans la vie d’un autre engage également celui qui agit et finit par revenir dans sa propre expérience."),
 T('associations-et-union','Associations et union','important','direct',[22,28,29,30,35,36,38,39],"La destinée se forme dans les associations. Le psaume oppose l’isolement qui affaiblit à la communion, au partage et à l’union autour d’un idéal commun, capables de constituer une force collective plus stable."),
 T('regard-qui-libere','Regard qui libère','important','direct',[25,33,34,37,38,39],"Le regard peut enfermer ou libérer. Le regard du sage refuse de figer l’autre dans un jugement définitif et considère les êtres comme capables d’évolution, ce qui transforme aussi l’orientation de celui qui regarde."),
]},
137:{'signals':['respect','concentration','espace','protection','non-ingérence'], 'themes':[
 T('respect-des-espaces','Respect des espaces','central','direct',[1,3,4,5,9,10,11,14,15,16,18,21,22],"Le psaume critique l’attitude qui s’impose partout sans reconnaître les limites et les besoins des autres. Le respect signifie savoir où l’on est invité, laisser aux êtres leur rythme et leur espace, et accepter que d’autres mondes puissent également poser leurs propres frontières."),
 T('concentration','Concentration','central','direct',[2,3,8,10,12,13,19],"La mouche symbolise l’agitation et la dispersion, tandis que la concentration permet de rester posé, de discerner un chemin et d’éviter les pièges créés par l’inconscience. La stabilité devient ici une condition de protection et de justesse."),
 T('non-ingerence','Non-ingérence','central','direct',[1,9,10,11,18,21,22],"Le sage n’impose ni son point de vue ni son rythme. Le texte demande de laisser les êtres faire leur expérience et de ne pas pénétrer dans leur monde sans nécessité ou invitation, même au nom d’une bonne intention."),
 T('protection-de-son-espace','Protection de son espace','important','direct',[14,15,16,18,19],"Respecter les autres n’implique pas de tout subir. L’homme doit savoir dire non, protéger son espace intérieur et refuser les influences qui l’empoisonnent ou l’éloignent de ce qu’il reconnaît comme juste et vrai."),
 T('positionnement','Positionnement','important','direct',[6,7,18,19,20],"Pour traverser les oppositions sans se perdre, l’homme doit savoir qui il est, ce qu’il veut et dans quel monde il choisit de vivre. Ce positionnement lui donne un corps de vérité plutôt qu’une identité changeante au gré des rencontres."),
 T('meditation-et-recul','Méditation et recul','important','direct',[8,12,13],"La méditation sert à se poser sur la Mère, éclaircir l’environnement intérieur et sortir de l’agitation réflexe. Elle crée la distance nécessaire pour percevoir les mondes et les influences avant d’agir."),
]},
138:{'signals':['chute de l’humanité','monde des entités','mémoire de l’origine','ciel humain','éducation'], 'themes':[
 T('memoire-de-l-origine','Mémoire de l’origine','central','direct',[1,2,3,4,5,8,9,12,13,15,24,25],"Le psaume décrit une mémoire profonde qui pousse l’homme à rechercher une origine au-delà de sa condition présente. La Tradition et l’éducation ont pour fonction de préserver ce lien afin qu’il ne soit pas entièrement recouvert par les créations du monde humain."),
 T('monde-des-entites','Monde des entités','central','direct',[7,10,11,12,14,17,19,20,22,23,26,27],"Le texte appelle « monde des entités » l’univers intermédiaire formé par les pensées, désirs et créations humaines devenus relativement autonomes. Ces formes finissent par influencer à leur tour l’homme et peuvent fermer l’accès à ce qui est présenté comme un monde supérieur réel."),
 T('ciel-cree-par-l-homme','Ciel créé par l’homme','central','direct',[7,9,10,11,12,18,19,20,21,24],"Le ciel humain est constitué d’idées, concepts et entités produits par l’activité mentale collective. À mesure qu’il s’épaissit, il devient un écran qui renvoie l’homme à ses propres créations plutôt qu’à une réalité autre que lui-même."),
 T('creation-inconsciente','Création inconsciente','important','direct',[7,10,14,17,19,23,26,27],"Pensées, désirs et paroles engendrent des formes qui cherchent ensuite à continuer leur existence. Le danger décrit par le psaume vient moins du pouvoir créateur lui-même que de son exercice inconscient, sans connaissance des conséquences."),
 T('tradition-comme-memoire','Tradition comme mémoire','important','direct',[4,5,12,15,24,25,26],"La Tradition est présentée comme une mémoire collective capable de conserver la science des mondes visibles et invisibles et de maintenir une voie de retour vers l’origine. Elle doit être étudiée et transmise pour éviter que l’homme ne soit enfermé dans son seul monde."),
 T('education-pour-ouvrir-le-ciel','Éducation pour ouvrir le ciel','important','direct',[12,15,24,25,26],"La réponse proposée est une éducation consciente : étudier, se former un corps de compréhension et d’action, identifier les mondes personnels et les formes héritées, puis agir de façon à desserrer progressivement leur emprise."),
]},
139:{'signals':['trois marches','dignité','concret','guérison','Bien commun'], 'themes':[
 T('reconquete-de-la-dignite','Reconquête de la dignité','central','direct',[5,6,7,8,10,12,14,17,19,20,21,22,26,27,28],"La dignité se reconquiert d’abord en soi par un processus conscient d’éducation, de guérison et de maîtrise. Elle devient ensuite une force capable de rendre leur valeur aux êtres et aux règnes autour de l’homme, jusqu’à élargir l’œuvre au Bien commun."),
 T('concret-contre-abstraction','Concret contre abstraction','central','direct',[9,10,11,12,14,15,16,23,24,25,28],"Le texte oppose les relations abstraites avec des mondes idéalisés à l’observation concrète de son propre monde. C’est dans les conséquences proches de ses pensées et actes que l’homme peut apprendre, recevoir un retour et sortir de la confusion."),
 T('guerison-de-son-propre-monde','Guérison de son propre monde','central','direct',[6,7,8,9,10,11,13,14,16,20,21,22],"Avant de prétendre guérir les autres règnes ou les mondes supérieurs, l’homme doit commencer par son propre monde. Étude, discipline et application permettent de rendre visibles ses incohérences et de reconstruire une relation plus stable avec ce qui l’entoure."),
 T('bien-commun-universel','Bien commun universel','important','direct',[7,8,17,18,19,20,25,26,28],"Le Bien commun n’est pas limité au groupe humain ou essénien. Il englobe tous les êtres et règnes, de sorte que l’éducation et les œuvres individuelles doivent progressivement devenir bénéfiques pour l’ensemble des mondes évoqués dans le texte."),
 T('stabilite-et-concentration','Stabilité et concentration','important','direct',[3,4,5,8,13,16,24,25],"La perte de dignité est reliée à la dispersion et au changement continuel de pensée ou d’humeur. La concentration rend l’homme lisible et fiable pour les mondes qui l’entourent, tandis que la stabilité ouvre la possibilité d’une œuvre durable."),
 T('progression-des-relations','Progression des relations','important','direct',[9,10,22,24,25,26,28],"Le psaume décrit une progression : restaurer d’abord sa propre dignité, puis œuvrer avec les règnes de la Mère, et enfin s’approcher des règnes supérieurs du Père. Cette montée repose sur une capacité acquise dans le réel plutôt que sur une revendication abstraite."),
]}}
def merge(e,n):
 by={t.get('themeId'):t for t in e}; [by.__setitem__(t['themeId'],t) for t in n]; o={t['themeId']:i for i,t in enumerate(n)}
 return sorted(by.values(),key=lambda t:(0 if t.get('themeId') in o else 1,o.get(t.get('themeId'),999),t.get('themeId','')))
def main():
 d=json.loads(PATH.read_text(encoding='utf-8')); by={a['number']:a for a in d['psalmAnalyses']}
 for num,s in DEEP.items(): by[num].update({'titleSignals':s['signals'],'themes':merge(by[num].get('themes',[]),s['themes']),'semanticDepth':'deep-content-grounded'})
 d['psalmAnalyses']=sorted(by.values(),key=lambda a:a['number']); m=d.setdefault('method',{}); m['semanticPass']='deepening-in-progress'; m['deepPsalmCount']=sum(a.get('semanticDepth')=='deep-content-grounded' for a in d['psalmAnalyses']); PATH.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n',encoding='utf-8'); print(f"Book 21 deep total={m['deepPsalmCount']}")
if __name__=='__main__': main()
