#!/usr/bin/env python3
"""Fifth close semantic pass for Michael book 21, Psalms 148-151, PDF-derived only."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; PATH=ROOT/'data/thematic-index/books/book-21.json'
def T(i,l,imp,d,v,t): return {'themeId':i,'label':l,'importance':imp,'directness':d,'verseNumbers':v,'teaching':t}
DEEP={
148:{'signals':['flamme de vie','intermédiaire','courage','règnes','capital divin'], 'themes':[
 T('flamme-de-vie','Flamme de vie','central','symbolic',[1,2,4,5,6,7,8,9,10,14,16,18,24,27,28,29,34],"La flamme de vie désigne ce qui doit être gardé actif, nourri et protégé dans l’homme. Le texte l’oppose à la résignation et au fonctionnement mécanique : être vivant suppose engagement, courage et capacité de faire fructifier ce qui a été reçu."),
 T('homme-intermediaire-des-mondes','Homme intermédiaire des mondes','central','direct',[11,12,13,19,20,21,22,29,30],"L’homme est présenté comme un passeur entre les mondes supérieurs et les règnes de la Mère. S’il bloque cette circulation dans son seul intérêt, les règnes situés en dessous de lui ne reçoivent plus, selon le texte, la nourriture et la bénédiction qu’il devait transmettre."),
 T('prendre-soin-de-la-vie','Prendre soin de la vie','central','direct',[5,6,9,10,16,27,28,29,34],"Prendre soin de la vie signifie reconnaître son caractère précieux et agir chaque jour pour l’entretenir. Les offrandes, les œuvres et les choix doivent augmenter la force disponible plutôt que laisser la flamme s’éteindre par négligence ou défaitisme."),
 T('courage-et-fidelite','Courage et fidélité','important','direct',[7,9,16,24,27,35],"Michaël associe la proximité de son feu au courage, à la fidélité et au refus d’abdiquer devant l’épreuve. La difficulté n’est pas niée, mais elle devient le lieu où l’homme montre s’il protège réellement ce qu’il dit tenir pour précieux."),
 T('responsabilite-envers-les-regnes','Responsabilité envers les règnes','important','direct',[11,12,13,14,19,20,21,22,29,30],"Le rapport aux règnes de la Mère sert de critère concret à la vie spirituelle. Une aspiration qui néglige animaux, végétaux, minéraux et terre est décrite comme incomplète parce qu’elle coupe la circulation que l’homme devait assurer."),
 T('capital-divin','Capital divin','important','symbolic',[28,29,34],"La flamme est aussi nommée capital divin : une puissance reçue qu’il faut faire fructifier avant qu’elle ne s’éteigne. Sa valeur se mesure aux œuvres et à la nourriture qu’elle permet d’apporter à plusieurs mondes."),
]},
149:{'signals':['porte des étoiles','eau magique','vérité','purification','institution'], 'themes':[
 T('porte-des-etoiles','Porte des étoiles','central','symbolic',[1,2,3,4,11,23,24,25,28,31,32],"La porte des étoiles représente un passage entre le monde humain et les mondes supérieurs que le texte demande de maintenir ouvert par une institution, une discipline et un corps collectifs. Elle ne repose donc pas sur une aspiration individuelle momentanée mais sur une structure transmissible."),
 T('eau-magique','Eau magique','central','symbolic',[10,12,13,14,16,19,20,21,22,23,27,28,29,30,34],"L’eau magique désigne le milieu subtil où pensées, regards, paroles et actes s’impriment. Elle devient le miroir de la vie quotidienne et le passage que toute pensée ou prière doit traverser avant de pouvoir atteindre les mondes supérieurs."),
 T('verite-de-l-eau','Vérité de l’eau','central','symbolic',[7,8,14,15,16,18,19,20,21],"L’eau est présentée comme révélant l’état réel de l’homme au-delà de l’image qu’il voudrait donner. Ce qui est vécu quotidiennement y laisse une trace, de sorte que la vérité du rapport aux mondes ne peut pas être remplacée par une apparence religieuse ponctuelle."),
 T('purification-du-milieu-interieur','Purification du milieu intérieur','important','direct',[22,24,25,27,31,32,33,34],"Étude, discipline, travail sur soi et soutien mutuel sont proposés pour nettoyer le milieu intérieur. La purification consiste notamment à interrompre les pensées et regards qui envahissent l’espace vital et à les remplacer par des atmosphères liées à la sagesse."),
 T('regard-et-reflet','Regard et reflet','important','direct',[17,19,20,29,30,33],"Le regard projette et reçoit des influences. Le monde perçu devient un miroir de ce que l’homme porte dans son cœur, tandis que les objets et êtres regardés peuvent à leur tour le féconder; d’où l’exigence de vigilance envers la manière de voir."),
 T('institution-comme-passage','Institution comme passage','important','direct',[2,3,4,24,25],"La Nation est décrite comme une structure qui doit conserver matériellement et collectivement le chemin ouvert. L’institution devient ainsi un corps de transmission capable de maintenir une possibilité de communication pour ceux qui viendront après."),
]},
150:{'signals':['mystères','Alliance','préparation','protection','Tradition vivante'], 'themes':[
 T('mysteres-sacres','Mystères sacrés','central','direct',[1,2,3,4,5,6,7,9,10,11,12,14,15,17,18,19,20,21,22,23,24,25],"Les mystères sont présentés non comme des informations secrètes mais comme une présence qui exige un milieu, une préparation et un corps capables de la porter. Lorsque seule la forme extérieure reste visible, le texte considère que le contenu vivant s’est retiré."),
 T('alliance-comme-corps-des-mysteres','Alliance comme corps des mystères','central','direct',[3,4,5,6,8,9,10,12,16,17,18,22,23,25],"L’Alliance est le corps qui permet aux symboles, rites et écritures d’être reliés à une présence vivante. Sans ce corps, une forme sacrée peut subsister matériellement mais son interprétation est décrite comme reprise par un autre monde."),
 T('preparation-et-initiation','Préparation et initiation','central','direct',[2,3,11,14,15,16,18,20,23,24,25],"L’accès aux mystères dépend d’une préparation qui développe les organes de compréhension nécessaires. La curiosité ou la possession d’un symbole ne suffisent pas : l’homme doit être formé pour rencontrer ce qui est présenté comme sacré sans le réduire à ses propres limites."),
 T('protection-du-sacre','Protection du sacré','important','direct',[1,2,3,8,9,10,11,19,20,22],"Protéger le sacré signifie préserver son intégrité face à l’avidité, la curiosité et l’usage profane. Le voile et la hiérarchie ne sont pas décrits comme une fin en soi mais comme les conditions qui empêchent une réalité d’être dénaturée par un regard non préparé."),
 T('tradition-vivante','Tradition vivante','important','direct',[5,6,17,23,25],"La Tradition naît de la transmission d’une expérience vivante et doit être régulièrement revivifiée. Une nouvelle époque ne reçoit pas nécessairement une doctrine nouvelle : le texte parle d’une même sagesse reformulée et réincarnée dans un corps adapté."),
 T('forme-et-presence','Forme et présence','important','direct',[12,15,18,19,23,25],"Une écriture, un symbole ou un rite ne sont pas considérés comme efficaces par leur seule forme. Leur valeur dépend du monde qui les habite et du corps vivant qui les relie à leur source, ce qui distingue lettre extérieure et présence intérieure."),
]},
151:{'signals':['capital d’énergie','étapes de vie','ciel et terre','investissement','mission'], 'themes':[
 T('capital-d-energie','Capital d’énergie','central','symbolic',[1,2,6,7,8,9,11,12,13,14,15,16,17,18,20,21,22,26,29,30,31,32,34],"L’énergie de vie est décrite comme un capital reçu à la naissance. Elle peut être dilapidée dans des activités sans retour ou transformée en force, en sagesse et en œuvres; la question centrale est donc celle de son orientation et de son investissement."),
 T('construire-ciel-et-terre','Construire ciel et terre','central','symbolic',[1,3,4,5,6,11,14,16,17,25,30,32],"L’homme doit utiliser son énergie pour construire simultanément une terre qui le porte et un ciel qui l’inspire. Ces deux images désignent les acquis concrets et subtils qui donnent continuité, stabilité et orientation à sa vie."),
 T('etapes-comme-epreuves','Étapes comme épreuves','central','direct',[6,9,14,15,16,17,18,19,20,21,22],"Les étapes de la vie sont présentées comme des moments où une part du capital doit être transformée. Une étape non accomplie affaiblit la capacité suivante, tandis qu’une étape menée à bien devient un organe ou un acquis qui conserve la force."),
 T('investissement-de-l-energie','Investissement de l’énergie','important','direct',[2,7,8,13,18,20,21,24,26,29,30,31],"L’énergie n’est pas supposée se renouveler automatiquement. Le texte demande de la concentrer et de la canaliser vers ce qui construit, ennoblit et prolonge la vie plutôt que vers des activités destinées seulement à maintenir une sensation d’existence."),
 T('mission-de-vie','Mission de vie','important','direct',[9,13,18,19,20,21,26,27,28,32,34],"Les circonstances sont interprétées comme des rappels d’une œuvre à accomplir. Retrouver la mémoire de cette mission permet de choisir où investir les forces restantes et de reprendre une capacité créatrice même lorsque beaucoup de temps a déjà passé."),
 T('transmission-aux-generations','Transmission aux générations','important','direct',[1,18,23,26,27],"La gestion du capital n’est pas seulement individuelle. Lorsque l’expérience est comprise tardivement, le texte demande encore de transmettre le savoir aux générations futures afin qu’elles puissent utiliser leur énergie avec plus de conscience."),
]}}
def merge(e,n):
 by={t.get('themeId'):t for t in e}; [by.__setitem__(t['themeId'],t) for t in n]; o={t['themeId']:i for i,t in enumerate(n)}
 return sorted(by.values(),key=lambda t:(0 if t.get('themeId') in o else 1,o.get(t.get('themeId'),999),t.get('themeId','')))
def main():
 d=json.loads(PATH.read_text(encoding='utf-8')); by={a['number']:a for a in d['psalmAnalyses']}
 for num,s in DEEP.items(): by[num].update({'titleSignals':s['signals'],'themes':merge(by[num].get('themes',[]),s['themes']),'semanticDepth':'deep-content-grounded'})
 d['psalmAnalyses']=sorted(by.values(),key=lambda a:a['number']); m=d.setdefault('method',{}); m['semanticPass']='deepening-in-progress'; m['deepPsalmCount']=sum(a.get('semanticDepth')=='deep-content-grounded' for a in d['psalmAnalyses']); PATH.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n',encoding='utf-8'); print(f"Book 21 deep total={m['deepPsalmCount']}")
if __name__=='__main__': main()
