#!/usr/bin/env python3
"""Third close semantic pass for Gabriel book 22, Psalms 146-149, PDF-derived only."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; PATH=ROOT/'data/thematic-index/books/book-22.json'
def T(i,l,imp,d,v,t): return {'themeId':i,'label':l,'importance':imp,'directness':d,'verseNumbers':v,'teaching':t}
DEEP={
146:{'signals':['mémoire','mission','identité','corps d’immortalité','tradition'], 'themes':[
 T('memoire-de-la-mission','Mémoire de la mission','central','direct',[1,2,4,5,6,7,8,9,10,11,15,17,20,21,27],"Le psaume relie l’identité profonde à une mission et à une œuvre que l’incarnation doit rendre visibles. La perte de mémoire détourne l’homme de ce but; la Tradition, l’apprentissage et l’action doivent progressivement réactiver ce souvenir et lui redonner un corps."),
 T('identite-au-dela-des-apparences','Identité au-delà des apparences','central','direct',[7,8,9,10,11,13,15,16,17],"Retrouver qui l’on est signifie ne plus réduire l’identité au corps et aux modèles reçus du monde humain. Le texte associe cette reconquête à un apprentissage conscient, à la maîtrise de l’instrument et à la manifestation concrète de ce qui est reconnu comme plus profond."),
 T('tradition-comme-memoire-vivante','Tradition comme mémoire vivante','central','direct',[8,9,11,13,19,24,27],"La Tradition est présentée comme le milieu familial et éducatif qui devrait préserver la mémoire de l’origine et de la mission. Lorsqu’elle est vivante, elle fournit des repères, une protection et un chemin de formation qui empêchent l’identité de se dissoudre dans les influences du milieu."),
 T('corps-d-immortalite','Corps d’immortalité','important','direct',[11,14,15,16,17,27],"Le cercle d’étude et les quatre pratiques sont reliés à la formation d’un corps destiné à traverser le voile de la mort. Ce corps doit être préparé par l’action, la discipline et l’intégration progressive de l’Enseignement."),
 T('digestion-avant-transmission','Digestion avant transmission','important','symbolic',[20,21],"Le texte demande de ne transmettre qu’un savoir déjà digéré, assimilé, compris et maîtrisé. La transmission vivante suppose donc une expérience réellement intégrée plutôt qu’une répétition de connaissances encore extérieures."),
 T('audace-et-action','Audace et action','important','direct',[12,17,18,23,24,25,26,28,30,31],"La mémoire ne se réveille pas par attente passive. Le psaume demande d’oser agir, d’ouvrir des passages, de créer des cercles et de poser des œuvres, tout en soumettant cette audace à l’éducation, à l’intelligence et au soutien mutuel."),
]},
147:{'signals':['pureté','eau','apparences','vertus vivantes','protection'], 'themes':[
 T('purete','Pureté','central','direct',[1,2,3,4,5,7,8,9,10,11,12,13,14,16,20,22,23,26,27,29,30],"La pureté est présentée comme une condition de vie, de vérité, de santé et de protection qui doit être rendue concrète dans les petites comme dans les grandes activités. Le texte oppose son entretien actif à une culture de la dégradation qui rend progressivement tout contact avec elle impossible."),
 T('eau-comme-milieu-de-purete','Eau comme milieu de pureté','central','symbolic',[13,14,15,16,17,18,19,20,21],"L’eau symbolise et matérialise un milieu de purification, de guérison et de renouvellement. Observer la qualité de l’eau des pensées, du cœur, des désirs et de l’aura devient un moyen de rendre visibles les états intérieurs et de travailler à leur clarification."),
 T('vertus-vivantes','Vertus vivantes','central','direct',[7,8,10,20,27,29,30],"Paix, amour, bienveillance et pureté ne doivent pas rester des mots. Elles sont décrites comme des réalités à fréquenter, nourrir et rendre vivantes par une attention régulière, faute de quoi leur signification et leur pouvoir disparaissent de la vie quotidienne."),
 T('discernement-des-apparences','Discernement des apparences','important','direct',[22,23,24,25,26],"La pureté ne peut pas être jugée sur l’apparence seule. Le texte demande de traverser les formes et d’observer les influences qui agissent derrière elles, car un visage ou un discours apparemment pur peut masquer un autre monde."),
 T('purete-comme-protection','Pureté comme protection','important','direct',[9,10,12,13],"La pureté est explicitement associée à la protection et à la possibilité de demeurer dans une atmosphère respirable pour les mondes décrits par le texte. La négliger revient à affaiblir le milieu dans lequel l’homme vit et se relie."),
 T('textes-comme-nourriture-pure','Textes comme nourriture pure','important','contextual',[27,28,29,30],"Le psaume présente les Évangiles esséniens comme une nourriture pure et une source d’inspiration. Cette relation est indexée comme affirmation interne du corpus, sans transformer cette qualification doctrinale en jugement externe."),
]},
148:{'signals':['homme véritable','méditation','observation','pensée vivante','échanges'], 'themes':[
 T('chemin-de-l-homme-veritable','Chemin de l’homme véritable','central','direct',[1,2,6,7,8,9,10,11,12,13,14,15,16,17,18,19],"Le chemin de l’homme véritable ne se réduit ni au matérialisme ni à l’idéalisme. Il passe par l’observation de la vie intérieure et extérieure, la méditation, l’étude et la vérification des alliances qui se manifestent dans la vie quotidienne."),
 T('meditation-comme-observation','Méditation comme observation','central','direct',[9,10,11,12,14,17,18,19,33],"La méditation est définie comme un art d’observation claire et vierge. Elle apprend à étudier les autres puis soi-même sans jugement afin de reconnaître les lois, les influences et les associations qui construisent effectivement une destinée."),
 T('vie-quotidienne-comme-miroir','Vie quotidienne comme miroir','central','direct',[14,15,16,17,29,31,32,33],"La vie quotidienne est le livre où les appartenances deviennent visibles. Pensées, actes et échanges révèlent les mondes servis et permettent de dépasser la séparation abstraite entre une vie matérielle et une vie spirituelle."),
 T('pensee-vivante','Pensée vivante','important','direct',[22,23,24,25,27,28,29],"La pensée est décrite comme une atmosphère réelle qui nourrit, anime et oriente le corps. L’observer permet de discerner les fils et affinités qui entraînent l’homme vers certaines habitudes, comportements et futurs."),
 T('eau-vers-le-centre','Eau vers le centre','important','symbolic',[20,21,24],"L’eau est associée au mouvement qui cherche le centre intérieur. Méditation, observation et étude doivent conduire cette énergie jusqu’au lieu de l’éveil plutôt que la laisser dispersée à la superficie de l’être."),
 T('echanges-conscients','Échanges conscients','important','direct',[31,32,33],"La vie est décrite comme un ensemble d’échanges inévitables. La sagesse consiste à les rendre conscients, justes et harmonieux afin qu’ils deviennent un chemin de libération plutôt qu’une chaîne d’associations subies."),
]},
149:{'signals':['eau magique','corps de terre','maîtrise','sensibilité subtile','alliance'], 'themes':[
 T('corps-d-eau','Corps d’eau','central','direct',[1,2,3,5,6,7,8,9,10,12,13,14,20,21,22,23,24],"Le corps d’eau désigne le milieu subtil qui entoure et relie pensées, états d’âme, volontés et influences. Le psaume demande de l’aborder comme une dimension à percevoir et maîtriser progressivement, à partir d’un corps physique déjà stabilisé."),
 T('maitrise-du-corps-de-terre','Maîtrise du corps de terre','central','direct',[4,6,7,9,13,14,15,16,17,18,19,20],"L’accès à une sensibilité plus subtile dépend d’une base corporelle calme, stable et disciplinée. Concentration, respiration, gestes et étude du corps doivent préparer la « barque » avant toute tentative de navigation dans l’eau magique."),
 T('purification-de-l-eau','Purification de l’eau','central','direct',[3,4,7,9,10,11,12,19,20],"Purifier l’eau consiste à réduire le trouble et le mélange en mettant ordre, cohérence et clarté dans les pensées, attitudes et mouvements. Une eau préparée devient dans le texte un espace de relation avec une intelligence plus haute."),
 T('sensibilite-aux-influences','Sensibilité aux influences','important','direct',[6,8,9,10,18,20,22,23,24],"La frontière du corps doit s’élargir à la perception des ambiances, présences et résonances. Cette sensibilité n’est pas recherchée pour elle-même mais afin de reconnaître ce qui influence le corps et d’agir avec davantage de discernement."),
 T('discipline-et-concentration','Discipline et concentration','important','direct',[4,6,15,16,17,18,19],"Silence, immobilité, concentration et rites structurent l’apprentissage. Ils permettent de calmer les réactions du corps physique et d’établir une base suffisamment stable pour observer ce qui se passe dans des couches plus fines de l’expérience."),
 T('alliance-par-le-corps-d-eau','Alliance par le corps d’eau','important','symbolic',[2,3,11,20,21,22],"Le corps d’eau pur est présenté comme un espace où une alliance peut être conclue et où la Lumière peut se rapprocher de la vie terrestre. Cette relation exige préparation, pureté et orientation vers le Bien commun plutôt qu’une recherche de pouvoir isolée."),
]}}
def merge(e,n):
 by={t.get('themeId'):t for t in e}; [by.__setitem__(t['themeId'],t) for t in n]; o={t['themeId']:i for i,t in enumerate(n)}
 return sorted(by.values(),key=lambda t:(0 if t.get('themeId') in o else 1,o.get(t.get('themeId'),999),t.get('themeId','')))
def main():
 d=json.loads(PATH.read_text(encoding='utf-8')); by={a['number']:a for a in d['psalmAnalyses']}
 for num,s in DEEP.items(): by[num].update({'titleSignals':s['signals'],'themes':merge(by[num].get('themes',[]),s['themes']),'semanticDepth':'deep-content-grounded'})
 d['psalmAnalyses']=sorted(by.values(),key=lambda a:a['number']); m=d.setdefault('method',{}); m['semanticPass']='deepening-in-progress'; m['deepPsalmCount']=sum(a.get('semanticDepth')=='deep-content-grounded' for a in d['psalmAnalyses']); PATH.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n',encoding='utf-8'); print(f"Book 22 deep total={m['deepPsalmCount']}")
if __name__=='__main__': main()
