#!/usr/bin/env python3
"""Fourth close semantic pass for Michael book 21, Psalms 144-147, PDF-derived only."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; PATH=ROOT/'data/thematic-index/books/book-21.json'
def T(i,l,imp,d,v,t): return {'themeId':i,'label':l,'importance':imp,'directness':d,'verseNumbers':v,'teaching':t}
DEEP={
144:{'signals':['intelligence','ordre','harmonie','pensée-sentiment-volonté','étude'], 'themes':[
 T('flamme-de-l-intelligence','Flamme de l’intelligence','central','direct',[1,2,3,7,8,9,10,14,15,16,18,20,22,23,25,26,27,28,31,32],"L’intelligence est présentée comme le principe qui remet chaque élément à sa juste place et éclaire les différents mondes de l’homme. L’étude doit allumer et entretenir cette intelligence afin qu’elle gouverne réellement la pensée, les sentiments, la volonté et l’acte."),
 T('ordre-et-harmonie','Ordre et harmonie','central','direct',[1,2,3,4,5,10,12,18,19,22,25,26,30],"Le psaume attribue la confusion à un mélange où les composantes de la vie ne sont plus accordées. L’ordre apparaît lorsque chaque monde est vrai dans sa fonction et relié à l’ensemble, ce qui transforme la réussite en problème d’harmonie plutôt que de simple efficacité."),
 T('unification-pensee-sentiments-volonte','Unification pensée-sentiments-volonté','central','direct',[5,6,10,13,14,17,23,24,29,30],"Pensée, sentiments et volonté ne doivent ni se contredire ni échanger leurs fonctions. La pensée éclairée doit équilibrer les sentiments puis conduire la volonté jusqu’à une réalisation concrète cohérente avec l’intelligence reconnue."),
 T('penser-en-lois','Penser en lois','important','direct',[8,9,10,15,20,27,28],"Penser en lois signifie nourrir la pensée d’un enseignement capable de relier plusieurs situations à une même intelligence. L’étude n’est donc pas une accumulation de notions mais une structuration de la pensée pour qu’elle devienne capable de jugement et d’orientation."),
 T('verite-dans-tous-les-mondes','Vérité dans tous les mondes','important','direct',[14,18,19,22,23],"La vérité recherchée doit pouvoir éclairer plusieurs dimensions sans isoler une seule perspective. Le texte oppose ainsi une vérité partielle ou idéaliste à une vérité qui ordonne, purifie et rend l’œuvre vivante dans l’ensemble."),
 T('oeuvre-comme-realisation-de-l-intelligence','Œuvre comme réalisation de l’intelligence','important','direct',[10,14,17,18,23,24,29,30,31],"L’œuvre doit porter jusque dans le concret l’intelligence qui l’a inspirée. Une réalisation est juste lorsque compréhension, amour, moyens, associations et acte final forment un seul corps au service d’une harmonie plus vaste."),
]},
145:{'signals':['équilibre','fil de la Tradition','deux mondes','vie terrestre','héritage'], 'themes':[
 T('equilibre-sur-le-fil','Équilibre sur le fil','central','symbolic',[1,2,3,4,5,6,9,22,25,26,27,28,29,30,31],"Le fil symbolise la voie étroite qui évite deux formes d’excès : l’absorption dans un mysticisme abstrait et l’enfermement dans le seul monde matériel. L’équilibre demande concentration, conscience des deux côtés et fidélité à une Tradition servant de repère."),
 T('tradition-comme-fil','Tradition comme fil','central','symbolic',[4,9,15,22,26,27,29,30,31],"La Tradition est décrite comme le fil qui maintient une conscience ouverte entre terre et ciel. Elle devient progressivement un pont lorsque les générations ajoutent des œuvres concrètes, des repères et une discipline qui rendent le passage plus stable pour ceux qui suivent."),
 T('vie-terrestre-comme-lieu-de-l-oeuvre','Vie terrestre comme lieu de l’œuvre','central','direct',[5,6,7,8,10,11,12,13,14,16,17,18,19,20,21,23,24],"La vie terrestre n’est pas dévalorisée au profit d’un au-delà. Elle est le lieu où santé, famille, travail, argent et œuvres doivent être équilibrés, car ce qui n’a pas été rencontré et réalisé ici ne devient pas automatiquement vivant dans un autre monde."),
 T('deux-mondes','Deux mondes','important','direct',[1,2,3,5,8,10,15,16,17,21,26,27,28,30],"Le texte demande de garder simultanément conscience du ciel et de la terre sans chercher la solution dans l’un contre l’autre. La justesse vient de leur relation et non de la fuite vers un monde supposé supérieur ou du refus de toute dimension subtile."),
 T('heritage-pour-les-generations','Héritage pour les générations','important','direct',[18,19,20,29,30],"Une œuvre équilibrée devient un héritage qui facilite le chemin des générations suivantes. Le psaume demande de laisser une terre et un ciel vivants, c’est-à-dire des traces, des structures et une orientation que d’autres pourront poursuivre."),
 T('equilibre-des-domaines-de-vie','Équilibre des domaines de vie','important','direct',[10,11,12,13,14],"Santé, foyer, travail et argent sont présentés comme des domaines à harmoniser concrètement. Aucun ne doit absorber toute la vie ni être abandonné à l’inconscience, car chacun participe au maintien de l’équilibre général."),
]},
146:{'signals':['dispersion','apparences','profondeur','individualité','aboutissement'], 'themes':[
 T('dispersion','Dispersion','central','direct',[9,10,11,12,15,19,21,22,29,30,31,33,34],"La dispersion empêche toute expérience de devenir profondeur, corps et maîtrise. Passer sans cesse d’une activité à l’autre donne une impression de liberté mais laisse les œuvres inachevées et l’homme sans résultat durable."),
 T('apparences','Apparences','central','direct',[2,3,5,8,9,21,23,26,27],"L’apparence fait croire à l’indépendance, au savoir ou à la réussite sans qu’un corps réel ait été construit. Le texte oppose cette surface séduisante à l’être véritable, qui demande effort, profondeur et accomplissement."),
 T('profondeur-et-corps','Profondeur et corps','central','direct',[9,10,11,12,14,27,28,29,31,33,34],"Connaître exige de se faire un corps avec ce qui est étudié plutôt que de survoler. Compréhension et action doivent progressivement s’unifier afin que l’intelligence puisse être conduite jusqu’à une manifestation tangible."),
 T('individualite-solide','Individualité solide','important','direct',[13,14,16,18,19],"L’individualité n’est pas assimilée à l’indépendance isolée. Elle est une stabilité acquise par l’étude, la concentration et la capacité d’achever une œuvre tout en restant relié à un ensemble plus vaste."),
 T('intelligence-collective','Intelligence collective','important','direct',[6,7,24,25,29,30],"Le texte présente l’existence comme un réseau de participation où chaque partie contribue au tout. Une œuvre juste est donc celle qui réintègre plusieurs êtres et règnes dans une cohésion et un Bien commun plutôt que de servir un centre isolé."),
 T('aboutissement','Aboutissement','important','direct',[12,15,17,19,20,22,30,31,33,34],"La force se mesure à la capacité de conduire ce qui a été compris jusqu’à l’aboutissement. L’intelligence, la compréhension et l’action doivent devenir un seul mouvement au lieu de rester trois corps séparés."),
]},
147:{'signals':['croix','croisée des chemins','feu','alliance','nature des associations'], 'themes':[
 T('croisee-des-chemins','Croisée des chemins','central','symbolic',[1,2,3,4,5,6,7,8,10,11,14,16],"La croisée des chemins représente le lieu de toute rencontre et de toute association. Ce qui s’y allume révèle la qualité du lien établi : chaque échange engendre une orientation et un feu qui transforment ceux qui y participent."),
 T('feu-des-rencontres','Feu des rencontres','central','symbolic',[2,3,4,5,6,7,8,9,10,12,13,14,15,16,17,18,19,20,23],"Le feu est l’effet vivant de la rencontre. Il peut éclairer et unir à une intelligence plus vaste ou devenir feu de décomposition; le discernement porte donc sur les conséquences concrètes et subtiles produites par l’échange."),
 T('alliance','Alliance','central','direct',[3,6,7,10,11,15,17],"Michaël est associé au mystère de l’Alliance parce que celle-ci naît lorsque deux mondes s’accordent autour d’un centre commun. L’alliance juste se reconnaît au feu qu’elle produit : clarté, purification et union à une intelligence durable."),
 T('nature-des-associations','Nature des associations','important','direct',[6,7,8,9,16,17,18],"La nature d’une association se lit dans ses fruits plutôt que dans son apparence. Le psaume demande d’observer ce que les échanges engendrent dans les émanations, les actes et la qualité intérieure pour savoir quel monde a réellement été rencontré."),
 T('sanctuaire-du-coeur','Sanctuaire du cœur','important','symbolic',[2,10,19,20],"Le centre de la croix est aussi présenté comme un sanctuaire intérieur qui doit rester pur. C’est là qu’un idéal supérieur doit être entretenu afin que les rencontres ne soient pas gouvernées automatiquement par des forces de décomposition."),
 T('feu-qui-consume-le-faux','Feu qui consume le faux','important','symbolic',[5,9,17,18,20,23],"Le feu de Michaël est décrit comme ce qui consume le faux et révèle la nature véritable des associations. À défaut d’une flamme consciente et orientée, c’est le feu du recyclage qui transforme ce qui n’a pas été relié à une valeur durable."),
]}}
def merge(e,n):
 by={t.get('themeId'):t for t in e}; [by.__setitem__(t['themeId'],t) for t in n]; o={t['themeId']:i for i,t in enumerate(n)}
 return sorted(by.values(),key=lambda t:(0 if t.get('themeId') in o else 1,o.get(t.get('themeId'),999),t.get('themeId','')))
def main():
 d=json.loads(PATH.read_text(encoding='utf-8')); by={a['number']:a for a in d['psalmAnalyses']}
 for num,s in DEEP.items(): by[num].update({'titleSignals':s['signals'],'themes':merge(by[num].get('themes',[]),s['themes']),'semanticDepth':'deep-content-grounded'})
 d['psalmAnalyses']=sorted(by.values(),key=lambda a:a['number']); m=d.setdefault('method',{}); m['semanticPass']='deepening-in-progress'; m['deepPsalmCount']=sum(a.get('semanticDepth')=='deep-content-grounded' for a in d['psalmAnalyses']); PATH.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n',encoding='utf-8'); print(f"Book 21 deep total={m['deepPsalmCount']}")
if __name__=='__main__': main()
