#!/usr/bin/env python3
"""Fifth close semantic pass for Gabriel book 22, Psalms 154-157, PDF-derived only."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; PATH=ROOT/'data/thematic-index/books/book-22.json'
def T(i,l,imp,d,v,t): return {'themeId':i,'label':l,'importance':imp,'directness':d,'verseNumbers':v,'teaching':t}
DEEP={
154:{'signals':['pièges de l’eau','projection','neutralité','vie quotidienne','éducation'], 'themes':[
 T('pieges-du-monde-de-l-eau','Pièges du monde de l’eau','central','symbolic',[1,2,3,4,5,6,8,10,11,19,20,21,23],"Le monde de l’eau est présenté comme un milieu où perceptions, désirs et croyances peuvent s’amplifier jusqu’à être pris pour une sagesse supérieure. Le piège consiste à confondre le reflet de sa propre vie intérieure avec une réalité objective."),
 T('projection-spirituelle','Projection spirituelle','central','direct',[5,8,9,10,11,15,19,22,23,26],"Le psaume critique les visions, intuitions et impressions utilisées comme autorité lorsqu’elles ne sont pas vérifiées. Une perception subtile peut simplement refléter les affinités et concepts de celui qui la reçoit; elle ne doit donc pas devenir automatiquement une parole supérieure."),
 T('neutralite-et-virginite','Neutralité et virginité','central','direct',[4,7,16,17,27,28],"Traverser l’eau exige de renoncer à l’intérêt personnel, au désir de résultat et à la volonté de diriger la perception. Le corps, le cœur, la volonté et l’intellect doivent être suffisamment calmes pour que l’observation ne soit pas immédiatement déformée par les attentes."),
 T('vie-quotidienne-comme-critere','Vie quotidienne comme critère','important','direct',[12,13,14,15,18],"Le texte replace la vérité dans la réalité vécue plutôt que dans un monde subtil abstrait. Organisation, travail, conséquences concrètes et capacité d’améliorer la vie deviennent des critères plus sûrs qu’une expérience spirituelle spectaculaire."),
 T('etude-des-lois','Étude des lois','important','direct',[6,9,16,18,24,27,28],"L’étude, l’éducation et la compréhension des lois fournissent une méthode de discernement plus stable que les impressions. Elles doivent former un corps de sagesse collectif capable de traverser les illusions sans les incarner dans le monde humain."),
 T('eau-force-ou-faiblesse','Eau comme force ou faiblesse','important','symbolic',[10,19,20,21],"La même eau est décrite comme force pour le sage et faiblesse pour celui qui abandonne le discernement. Elle amplifie ce qu’elle reçoit; sa valeur dépend donc de l’éducation, de la pureté et de la maîtrise de celui qui la traverse."),
]},
155:{'signals':['vie après la mort','eau','passage','relations','discernement'], 'themes':[
 T('vie-apres-la-mort-comme-continuite','Vie après la mort comme continuité','central','contextual',[1,2,3,4,6,7,8,9,14,21,22],"Le psaume affirme que le passage après la mort prolonge la qualité de l’eau et des associations cultivées durant la vie. Cette relation est indexée comme doctrine interne du texte : la mort n’y est pas décrite comme libération automatique mais comme continuité d’un état déjà formé."),
 T('passage-de-l-eau','Passage de l’eau','central','symbolic',[2,3,4,9,10,11,12,14,16,18,19,20,21],"Le passage de l’eau représente un travail à accomplir pendant la vie terrestre : reconnaître, nettoyer et traverser les influences qui entourent l’homme. Le texte insiste sur le fait que ce travail ne peut pas être différé en espérant que la mort résoudra ce qui n’a pas été transformé."),
 T('memoire-des-ages','Mémoire des âges','central','symbolic',[12,13,14,15],"L’eau est décrite comme portant les écritures du passé, du présent et du devenir. Transformer cette mémoire signifie étudier les schémas hérités et leur donner une autre orientation à travers une vie et une œuvre plus conscientes."),
 T('relations-justes','Relations justes','important','direct',[23,24,25,26,27,28,29,30,31,32],"Le travail du cercle doit se prolonger dans les relations quotidiennes. Un oui clair, un non clair et le discernement des influences permettent de ne pas laisser une relation devenir le véhicule de mondes qui détournent la destinée."),
 T('corps-stable-par-l-enseignement','Corps stable par l’Enseignement','important','direct',[15,16,20,21,23],"L’Enseignement doit former un corps et une vie stables qui donnent une base au passage. Alléger les liens, créer un cadre et répéter le travail dans la vie quotidienne permettent de transformer progressivement la manière d’entrer en relation avec l’eau."),
 T('mort-ne-resout-pas-le-non-accompli','La mort ne résout pas le non-accompli','important','contextual',[7,8,9,10,11,21,22],"Le texte refuse explicitement l’idée que la mort répare ce qui n’a pas été travaillé dans la vie. Cette affirmation est conservée comme enseignement du corpus, sans être présentée comme constat vérifié en dehors de celui-ci."),
]},
156:{'signals':['artisans de la paix','semence','discernement','corps de paix','création'], 'themes':[
 T('artisans-de-la-paix','Artisans de la paix','central','direct',[1,2,3,14,16,17,29,30,31,32,33,34],"La paix n’est pas seulement un état à souhaiter : elle doit recevoir une terre, un corps et des actes capables de la rendre vivante. L’homme est présenté comme un artisan chargé de protéger une semence et de la conduire jusqu’à une manifestation concrète."),
 T('corps-de-la-paix','Corps de la paix','central','symbolic',[16,29,30,31,32,33,34,35,36],"Créer le corps de la paix signifie former en soi un état méditatif, maîtrisé et cohérent, puis bâtir un milieu où cette paix peut agir. Ce corps devient une œuvre et, dans la logique du psaume, un élément du corps d’immortalité."),
 T('discernement-des-semences','Discernement des semences','central','symbolic',[4,5,6,8,9,10,18,19,20,21,25,28],"Pensées, idées et principes sont décrits comme des semences portées par des intelligences. Le discernement consiste à identifier ce qui féconde la terre intérieure et collective avant de transmettre ou d’incarner une orientation qui n’a pas été réellement comprise."),
 T('ne-transmettre-que-ce-qui-est-porte','Ne transmettre que ce qui est porté','important','direct',[21,22,23,24,25],"Le psaume demande de ne pas prononcer ni enseigner ce qui n’est pas compris et maîtrisé. Une parole ou une direction ne devient légitime qu’après avoir été intégrée à la vie de celui qui la transmet."),
 T('etude-meditation-action','Étude, méditation et action','important','direct',[11,12,13,14,20,21,26,27,28,31,32],"Étude, dévotion, rite, méditation, concentration et action consciente forment un chemin progressif. Elles doivent permettre de peser les influences, transformer les trois centres de l’homme et avancer pas à pas vers une œuvre plus juste."),
 T('source-interieure','Source intérieure','important','symbolic',[1,6,21,25,28,35,36],"L’homme doit créer depuis une source intérieure reliée à une intelligence supérieure plutôt que reproduire les semences dominantes du monde environnant. Soutenir l’œuvre commune sert aussi à reconstruire cette capacité créatrice lorsqu’elle est encore faible."),
]},
157:{'signals':['22 arcanas','étapes','corps de sagesse','transmission','clés'], 'themes':[
 T('vingt-deux-arcanas','22 arcanas','central','direct',[4,5,6,7,8,9,10,11,12,14,15,16,18,20,21,22,28,30,32],"Les 22 arcanas et commandements sont présentés comme une progression ordonnée, comparable aux marches d’une pyramide. Chacun doit être vécu et stabilisé avant le suivant afin que l’ensemble forme un corps de sagesse plutôt qu’une connaissance incomplète."),
 T('etapes-et-stabilisation','Étapes et stabilisation','central','direct',[1,2,3,4,5,7,11,30],"Le psaume insiste sur la patience et le refus de brûler les étapes. Chaque marche doit devenir un fondement acquis par compréhension, discipline et réalisation consciente avant que l’homme poursuive son ascension."),
 T('corps-de-sagesse','Corps de sagesse','central','direct',[5,6,7,9,12,28,30,32],"La formation progressive doit construire un corps capable de traverser l’eau et de soutenir une identité supérieure. Les commandements doivent devenir aussi concrets et nécessaires que les nourritures qui entretiennent le corps physique."),
 T('commandements-comme-cles','Commandements comme clés','important','symbolic',[15,16,22,28,29,30],"Chaque commandement est décrit comme une clé ouvrant un monde et un passage. Le porteur de clé n’ouvre pas seulement pour lui-même : il devient gardien de la porte et doit discerner comment transmettre l’accès aux autres."),
 T('transmission-aux-generations','Transmission aux générations','important','direct',[10,12,13,14,16,17,18,21],"La pratique des commandements est explicitement reliée à la transmission. Ce qui est reçu doit être conservé vivant, ancré dans la terre et offert aux générations futures comme une orientation et non comme une forme morte."),
 T('tradition-incarnee','Tradition incarnée','important','direct',[9,14,18,20,21,23,24,25,26,27,28,31,32],"La Tradition se manifeste sous plusieurs formes — enseignements, rites, Évangiles, commandements — qui doivent toutes devenir vécues. Leur continuité dépend de personnes qui les intègrent au quotidien jusqu’à ce qu’elles deviennent une seconde nature consciente."),
]}}
def merge(e,n):
 by={t.get('themeId'):t for t in e}; [by.__setitem__(t['themeId'],t) for t in n]; o={t['themeId']:i for i,t in enumerate(n)}
 return sorted(by.values(),key=lambda t:(0 if t.get('themeId') in o else 1,o.get(t.get('themeId'),999),t.get('themeId','')))
def main():
 d=json.loads(PATH.read_text(encoding='utf-8')); by={a['number']:a for a in d['psalmAnalyses']}
 for num,s in DEEP.items(): by[num].update({'titleSignals':s['signals'],'themes':merge(by[num].get('themes',[]),s['themes']),'semanticDepth':'deep-content-grounded'})
 d['psalmAnalyses']=sorted(by.values(),key=lambda a:a['number']); m=d.setdefault('method',{}); m['semanticPass']='deepening-in-progress'; m['deepPsalmCount']=sum(a.get('semanticDepth')=='deep-content-grounded' for a in d['psalmAnalyses']); PATH.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n',encoding='utf-8'); print(f"Book 22 deep total={m['deepPsalmCount']}")
if __name__=='__main__': main()
