#!/usr/bin/env python3
"""Second close semantic pass for Gabriel book 22, Psalms 142-145, PDF-derived only."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; PATH=ROOT/'data/thematic-index/books/book-22.json'
def T(i,l,imp,d,v,t): return {'themeId':i,'label':l,'importance':imp,'directness':d,'verseNumbers':v,'teaching':t}
DEEP={
142:{'signals':['fixité','mouvement','Tradition','stabilité','corps collectif'], 'themes':[
 T('fixite-dans-le-mouvement','Fixité dans le mouvement','central','symbolic',[2,3,7,14,15,34],"La fixité dans le mouvement associe un centre stable à une capacité de respirer, rayonner et agir. Le psaume l’illustre par un corps solidement posé qui ne se laisse pas déraciner par les influences tout en restant vivant et mobile dans sa manifestation."),
 T('tradition-comme-corps','Tradition comme corps','central','direct',[1,2,4,10,11,20,22,32],"La Tradition est présentée comme le corps collectif formé par des êtres suffisamment stables pour accueillir et porter une intelligence supérieure. Elle doit unir éducation, organisation et réalisation concrète jusqu’à fournir une véritable terre de manifestation."),
 T('stabilite-et-enracinement','Stabilité et enracinement','central','direct',[3,6,7,8,14,15,16,17,32],"La stabilité protège l’œuvre contre les courants contraires et les variations d’humeur ou d’environnement. La pierre et l’enracinement servent de modèles à une fidélité intérieure capable de tenir le cap même lorsque le monde autour devient incohérent."),
 T('organisation-individuelle-et-collective','Organisation individuelle et collective','important','direct',[10,12,14,20,22,23,24,25,26,27,28],"Le corps de la Lumière doit être préparé à la fois individuellement et collectivement. Une vie quotidienne organisée, des engagements clairs et le soutien mutuel transforment une aspiration en structure assez solide pour porter une œuvre plus vaste."),
 T('service-de-la-lumiere','Service de la Lumière','important','direct',[5,17,19,20,21,22,24],"La Lumière n’est pas appelée pour conforter la vie mortelle mais pour être servie et recevoir un corps. L’homme doit donc se rendre disponible, bâtir et prendre soin des conditions qui permettent à ce qu’il reconnaît comme supérieur de toucher la terre."),
 T('union-et-soutien-mutuel','Union et soutien mutuel','important','direct',[25,26,27,28,29,30,31],"Le psaume insiste sur l’impossibilité de porter seul une force décrite comme plus grande que chacun. L’union, la clarté relationnelle et le refus de la division deviennent des conditions de réussite du corps collectif."),
]},
143:{'signals':['protection','capital-Lumière','alliances','responsabilité','relations'], 'themes':[
 T('protection-divine','Protection divine','central','direct',[1,2,3,4,5,7,8,9,11,12,17,23,27,28],"La protection est présentée comme une condition de vie qui doit être entretenue et renforcée, non comme un acquis automatique. Elle dépend de la qualité du lien conservé avec ce que le texte décrit comme supérieur et bénéfique."),
 T('protection-comme-capital','Protection comme capital','central','symbolic',[4,5,10,12,19,22,28],"Le psaume compare la protection à un capital reçu en héritage. Pensées, sentiments et actes peuvent le préserver, l’accroître ou le dilapider; la responsabilité consiste donc à ne pas dévaluer ce qui a été confié."),
 T('bonnes-alliances','Bonnes alliances','central','direct',[13,14,15,17,25,26,27],"La protection passe par des associations cohérentes dans les mondes visibles et invisibles. Le texte demande de choisir consciemment les liens entretenus, car la nature des alliances finit par déterminer la qualité des influences et du devenir."),
 T('ennoblissement','Ennoblissement','important','direct',[19,20,21,22,23],"Pensée, parole, regard, actes et êtres sont décrits comme porteurs d’une valeur qui ne doit pas être avilie. Ennoblir signifie prendre soin de l’héritage reçu et conduire les relations vers davantage de conscience et de sagesse."),
 T('homme-canal-de-benediction','Homme comme canal de bénédiction','important','symbolic',[17,18,23],"L’homme est présenté comme un canal capable de recevoir une eau pure puis de la transmettre à d’autres mondes. Cette fonction suppose un corps et une conduite suffisamment maîtrisés pour que la bénédiction ne soit pas interrompue ou dénaturée."),
 T('relations-et-futur','Relations et futur','important','direct',[14,15,25,26,27],"Le futur est relié à la nature des relations entretenues. Les associations choisies attirent des mondes plus vastes qui, dans la logique du psaume, renforcent à leur tour une orientation de vie et une capacité d’action."),
]},
144:{'signals':['impersonnalité','ombre personnelle','rééducation','neutralité','disciple'], 'themes':[
 T('impersonnalite','Impersonnalité','central','direct',[1,2,3,4,6,15,17,19,20,21,25,26,27,28],"L’impersonnalité est la porte qui permet de sortir du point de vue étroit centré sur le corps et l’intérêt personnel. Elle ouvre à une perception plus neutre, universelle et disponible à une intelligence qui n’est pas ramenée aux préférences de l’individu."),
 T('ombre-personnelle','Ombre personnelle','central','symbolic',[8,10,11,13,14,15,16,18],"Le texte appelle « ombre » la tendance à ramener toute relation, générosité ou quête spirituelle à la préservation et à la valorisation du moi mortel. Cette ombre déforme la perception en faisant du point de vue personnel la mesure de toute chose."),
 T('reeducation-a-l-universel','Rééducation à l’universel','central','direct',[7,15,16,17,20,21,22,23,25],"L’impersonnalité doit être réapprise par une éducation consciente, une discipline et une communauté structurée. L’objectif est de rendre possible un regard qui ne soit plus entièrement déterminé par les habitudes et réflexes acquis."),
 T('neutralite-et-virginite','Neutralité et virginité','important','symbolic',[4,15,19,20,21,22,27],"La neutralité est figurée par une coupe vide et transparente. Elle consiste à suspendre les projections personnelles pour recevoir une situation ou un enseignement avec assez de calme et de pureté pour distinguer les influences réellement à l’œuvre."),
 T('disciple-et-maitre','Disciple et maître','important','direct',[22,23,24,26,28],"Le chemin du discernement est relié à la discipline du disciple et à l’acquisition d’un autre regard, appelé l’œil du maître. Étudier les textes avec ce regard doit progressivement modifier la manière de penser et d’interpréter."),
 T('corps-impersonnel-et-universel','Corps impersonnel et universel','important','direct',[19,28,29],"L’étude et les pratiques doivent former un corps distinct du simple corps mortel, capable de stabiliser la vie et de servir une sagesse plus universelle. Le texte associe ce corps à la possibilité de vivre et d’agir dans plusieurs mondes."),
]},
145:{'signals':['liberté','légèreté','choix','dépendance','objectif'], 'themes':[
 T('liberte-comme-concept','Liberté comme concept','central','direct',[1,2,3,4,5,6,8,20],"Le psaume conteste la liberté conçue comme autonomie absolue de l’individu. Dans sa logique interne, tout être dépend de mondes, de nourritures et de relations; la question n’est donc pas de devenir sans liens mais de devenir conscient de ceux qui orientent la vie."),
 T('legerete','Légèreté','central','direct',[7,8,10,11,12,17,19,24,25,26,27],"La légèreté est proposée comme vertu praticable : ne pas accumuler des charges inutiles, rester mobile et conserver assez de conscience pour poursuivre une œuvre. Plus l’homme s’alourdit de liens et de mondes non choisis, plus sa marge d’action diminue."),
 T('choix-du-monde','Choix du monde','central','direct',[10,16,17,18,19,25],"La forme de liberté reconnue par le texte réside dans la possibilité de choisir consciemment le monde que l’on accepte de servir et de laisser agir à travers soi. Ce choix exige éveil, mémoire, éducation et une orientation suffisamment claire."),
 T('dependance-et-nourriture','Dépendance et nourriture','important','direct',[3,4,5,9,10,12],"L’homme est décrit comme dépendant des nourritures physiques, psychiques, intellectuelles et spirituelles qu’il reçoit. Ces nourritures forment un corps et une destinée, d’où la nécessité de discerner ce qui allège ou alourdit."),
 T('coherence-pensee-parole-acte','Cohérence pensée-parole-acte','important','direct',[22,23],"La dignité et la santé de la vie demandent une cohérence entre pensée, parole et action. Penser une chose, dire son contraire puis agir autrement produit, selon le texte, confusion et faiblesse plutôt qu’une véritable capacité de choix."),
 T('objectif-et-concentration','Objectif et concentration','important','direct',[25,26,27,28],"La légèreté se protège par un objectif clair. Tout ce qui approche doit être évalué selon sa contribution à ce but, tandis que la concentration et la maîtrise des sens empêchent la dispersion et le détournement de l’orientation initiale."),
]}}
def merge(e,n):
 by={t.get('themeId'):t for t in e}; [by.__setitem__(t['themeId'],t) for t in n]; o={t['themeId']:i for i,t in enumerate(n)}
 return sorted(by.values(),key=lambda t:(0 if t.get('themeId') in o else 1,o.get(t.get('themeId'),999),t.get('themeId','')))
def main():
 d=json.loads(PATH.read_text(encoding='utf-8')); by={a['number']:a for a in d['psalmAnalyses']}
 for num,s in DEEP.items(): by[num].update({'titleSignals':s['signals'],'themes':merge(by[num].get('themes',[]),s['themes']),'semanticDepth':'deep-content-grounded'})
 d['psalmAnalyses']=sorted(by.values(),key=lambda a:a['number']); m=d.setdefault('method',{}); m['semanticPass']='deepening-in-progress'; m['deepPsalmCount']=sum(a.get('semanticDepth')=='deep-content-grounded' for a in d['psalmAnalyses']); PATH.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n',encoding='utf-8'); print(f"Book 22 deep total={m['deepPsalmCount']}")
if __name__=='__main__': main()
