#!/usr/bin/env python3
"""Sixth close semantic pass for Gabriel book 22, Psalms 158-161, PDF-derived only."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; PATH=ROOT/'data/thematic-index/books/book-22.json'
def T(i,l,imp,d,v,t): return {'themeId':i,'label':l,'importance':imp,'directness':d,'verseNumbers':v,'teaching':t}
DEEP={
158:{'signals':['gratitude','apprécier','plénitude','vie intérieure','préserver'], 'themes':[
 T('apprecier-ce-que-l-on-a','Apprécier ce que l’on a','central','direct',[4,5,6,7,8,10,11,12,14,15,19,20,21,22,23,28],"Le psaume critique l’insatisfaction qui cherche toujours ailleurs ce qui manque et finit par dévaluer ce qui est déjà vivant. Apprécier signifie reconnaître, protéger et faire fructifier les capacités, relations et conditions reçues au lieu d’attendre leur perte pour découvrir leur valeur."),
 T('gratitude','Gratitude','central','direct',[10,11,12,14,15,16,19,21,22,23],"La gratitude est associée au goût de vivre et à la capacité de rester relié à ce qui nourrit réellement l’existence. Elle transforme les actes ordinaires — respirer, marcher, penser, travailler — en réalités reconnues plutôt qu’en habitudes devenues invisibles."),
 T('equilibre-interieur-exterieur','Équilibre intérieur-extérieur','important','direct',[7,8,9,15,20],"Chercher davantage de moyens extérieurs n’est pas condamné, mais le texte demande de préserver en même temps la vie intérieure et l’essentiel déjà présent. L’équilibre empêche les projets de devenir une fuite permanente vers le superflu."),
 T('preserver-la-vie','Préserver la vie','central','direct',[10,11,14,16,17,18,19,24,28,29,30,31],"La vie doit être activement respectée et défendue contre les attitudes qui la rendent fade, mécanique ou fataliste. Le texte appelle à maintenir des valeurs vivantes et une capacité créatrice même dans un contexte perçu comme difficile."),
 T('changer-de-point-de-vue','Changer de point de vue','important','direct',[17,18,28,31,32,33],"L’impression d’impasse peut provenir d’un monde qui impose un seul angle de lecture. Le psaume invite à reconnaître la pluralité des vies et intelligences présentes afin de retrouver une possibilité d’action et de ne pas se laisser enfermer par le découragement."),
 T('education-de-la-lumiere','Éducation de la Lumière','important','direct',[1,2,3,13,19,31],"L’éducation est présentée comme ce qui nourrit l’âme et donne un autre rapport à la vie. Elle doit réapprendre à reconnaître les trésors reçus, à les conserver et à les transmettre plutôt qu’à construire l’existence sur le manque permanent."),
]},
159:{'signals':['mort','préparation','alliances','corps','vie quotidienne'], 'themes':[
 T('preparer-la-mort-en-vivant','Préparer la mort en vivant','central','contextual',[1,2,3,4,5,6,8,9,10,11,12,13,14,16,18,20],"Le psaume présente la préparation à la mort comme un travail effectué durant la vie : clarifier les intérêts, les pensées, les états d’âme et les alliances qui structurent le quotidien. Cette doctrine est indexée comme contenu interne du texte, sans être présentée comme connaissance extérieure vérifiée."),
 T('on-part-comme-on-a-vecu','On part comme on a vécu','central','contextual',[5,6,8,9,10,11,12,16,20,25,26],"Dans la logique du psaume, les centres d’intérêt, habitudes et écritures cultivés durant la vie deviennent le milieu rencontré après la mort. La continuité entre vie quotidienne et passage constitue l’axe majeur de cet enseignement."),
 T('alliances-vivantes','Alliances vivantes','central','direct',[13,14,16,17,18,20,23],"Les alliances ne sont pas décrites comme de simples croyances mais comme des liens rendus actifs dans les actes et les choix. Elles construisent un corps, orientent le chemin et fournissent les repères auxquels l’homme pourra reconnaître ce qu’il a réellement servi."),
 T('maitrise-pendant-le-passage','Maîtrise pendant le passage','important','contextual',[7,8,9,10,12,13],"Le texte associe le passage à la capacité de rester clair au milieu d’images et d’influences amplifiées. La maîtrise des pensées, états d’âme et du corps durant la vie est présentée comme préparation à cette vigilance."),
 T('corps-vaisseau-de-sagesse','Corps comme vaisseau de sagesse','important','direct',[6,7,21,24,25,26,27,28,29,30,31],"Le corps n’est pas traité comme un simple véhicule jetable : il enregistre les expériences et sert d’instrument d’ennoblissement. En prendre soin signifie l’organiser pour qu’il transmette aux autres dimensions de la vie ce qui a été appris et réalisé."),
 T('equilibre-enseignement-quotidien','Équilibre Enseignement-vie quotidienne','important','direct',[20,21,22,23,27],"Le psaume demande de ne pas séparer philosophie et vie active. Une activité qui devient nocive doit être corrigée, tandis que le quotidien doit devenir le lieu où l’Enseignement est réellement éprouvé et ajusté."),
]},
160:{'signals':['vision magique','contexte','éléments vivants','responsabilité','nommer'], 'themes':[
 T('vision-magique-de-la-vie','Vision magique de la vie','central','direct',[1,2,3,4,5,6,7,8,9,10,11,12,14,15,16,17,18,21,25,27,28,29,30],"La vision magique demandée consiste à considérer les éléments, êtres et choses comme reliés à un contexte, une origine et une fonction plutôt que comme objets isolés. L’homme doit devenir conscient du sens qu’il attribue à ce qu’il extrait de son milieu et de la responsabilité qui en découle."),
 T('respect-du-contexte','Respect du contexte','central','direct',[3,4,5,6,7,8,9,10,13,17,20,22,26,30],"Séparer un élément de son monde sans lui donner de fonction est présenté comme une dégradation. Le texte demande de maintenir symboliquement le lien avec la source, de reconnaître l’origine et d’éviter de réduire les êtres à des usages détachés de leur contexte."),
 T('nommer-et-donner-une-fonction','Nommer et donner une fonction','central','direct',[6,7,10,12,16,17,20,25,28,29,30],"Nommer signifie rendre conscient l’usage d’un élément extrait de son milieu. Une fonction claire l’intègre à la vie et à une intention déterminée, ce qui empêche, dans la logique du psaume, qu’un autre monde lui attribue à la place de l’homme une écriture étrangère."),
 T('responsabilite-envers-les-elements','Responsabilité envers les éléments','important','direct',[7,13,15,16,17,18,19,20,26,27,29],"Pouvoir utiliser eau, feu, terre, plantes ou autres êtres implique d’en assumer la responsabilité. L’homme doit préserver leur dignité, leur relation à leur origine et leur orientation vers le Bien plutôt que les laisser devenir des instruments sans conscience."),
 T('homme-a-la-frontiere-des-mondes','Homme à la frontière des mondes','important','direct',[1,2,3,9,22],"L’homme est situé entre plusieurs règnes et mondes et peut contribuer à leur communication ou à leur séparation. Sa propre faiblesse augmente lorsqu’il oublie sa source, tout comme les éléments qu’il coupe de leur contexte deviennent vulnérables."),
 T('tout-est-vivant','Tout est vivant','important','direct',[4,6,8,10,11,12,15,16,25,29],"Feu, eau, air, terre, savoir et vertus sont traités comme des réalités vivantes. Cette perspective fonde une morale de l’usage : rien ne doit être employé machinalement sans conscience de sa relation, de son rôle et de son devenir."),
]},
161:{'signals':['vie','immortalité','écriture vivante','création','unification'], 'themes':[
 T('vie-cle-de-l-immortalite','Vie, clé de l’immortalité','central','contextual',[1,2,3,4,5,6,8,10,11,12,13,15,18],"Le psaume affirme que seule la vie — ce qui est animé, fécond et capable de se reproduire — ouvre le chemin de l’immortalité. Cette affirmation doctrinale est indexée comme structure interne du texte : rendre vivant ce qui est appris et accompli y devient le critère essentiel."),
 T('ecriture-vivante','Écriture vivante','central','symbolic',[5,6,7,8,11,12,13,14,15,18],"Écrire dans les mondes signifie donner vie, sens et continuité à des symboles, paroles et œuvres jusque dans le quotidien. Une écriture devient opérante lorsqu’elle est incarnée et reconnue par l’homme comme partie de sa propre vie."),
 T('creer-ce-que-l-on-veut-voir','Créer ce que l’on veut voir','central','direct',[8,9,11,13,15,18],"L’homme doit être créateur du monde qu’il veut voir apparaître. Il ne suffit pas de connaître des symboles ou une tradition : il faut les vivifier par l’énergie, l’activité et l’incarnation jusqu’à ce qu’ils deviennent une réalité vécue."),
 T('tradition-vivifiee','Tradition vivifiée','important','direct',[11,12,13,15],"La Tradition ne doit pas rester une philosophie ou un concept. Les symboles, écritures et enseignements doivent être nourris par l’activité créatrice de ceux qui les portent afin qu’ils puissent rester reliés à une intelligence vivante."),
 T('unification-des-regnes-et-des-mondes','Unification des règnes et des mondes','important','direct',[16,17,18],"L’immortalité est associée dans le texte à une unification : minéral, végétal, animal, mondes angéliques et vie humaine doivent être intégrés à un même chemin plutôt que maintenus dans la séparation."),
 T('bien-commun-comme-oeuvre-vivante','Bien commun comme œuvre vivante','important','direct',[17,18],"L’œuvre atteint le Bien commun lorsqu’elle relie la pierre au monde des Dieux et fait vivre plusieurs règnes dans une même écriture. L’homme devient alors vivant de ce qu’il a lui-même contribué à rendre vivant."),
]}}
def merge(e,n):
 by={t.get('themeId'):t for t in e}; [by.__setitem__(t['themeId'],t) for t in n]; o={t['themeId']:i for i,t in enumerate(n)}
 return sorted(by.values(),key=lambda t:(0 if t.get('themeId') in o else 1,o.get(t.get('themeId'),999),t.get('themeId','')))
def main():
 d=json.loads(PATH.read_text(encoding='utf-8')); by={a['number']:a for a in d['psalmAnalyses']}
 for num,s in DEEP.items(): by[num].update({'titleSignals':s['signals'],'themes':merge(by[num].get('themes',[]),s['themes']),'semanticDepth':'deep-content-grounded'})
 d['psalmAnalyses']=sorted(by.values(),key=lambda a:a['number']); m=d.setdefault('method',{}); m['semanticPass']='deepening-in-progress'; m['deepPsalmCount']=sum(a.get('semanticDepth')=='deep-content-grounded' for a in d['psalmAnalyses']); PATH.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n',encoding='utf-8'); print(f"Book 22 deep total={m['deepPsalmCount']}")
if __name__=='__main__': main()
