#!/usr/bin/env python3
"""Fourth close semantic pass for Gabriel book 22, Psalms 150-153, PDF-derived only."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; PATH=ROOT/'data/thematic-index/books/book-22.json'
def T(i,l,imp,d,v,t): return {'themeId':i,'label':l,'importance':imp,'directness':d,'verseNumbers':v,'teaching':t}
DEEP={
150:{'signals':['persévérance','clarté','relations','fidélité','Bien commun'], 'themes':[
 T('perseverance','Persévérance','central','direct',[6,7,8,9,10,11,12,13,32,34],"La persévérance permet de traverser doute, obstacle et fatigue sans abandonner l’engagement. Elle transforme l’épreuve en force et conduit une œuvre jusqu’à son aboutissement, à condition de rester fidèle aux lois et au but choisi."),
 T('eau-des-relations','Eau des relations','central','symbolic',[15,16,17,18,20,22,23,24,25,27,28,30,31],"Les relations sont décrites comme une eau qui peut devenir claire ou trouble selon regards, paroles, conflits et intentions. La nettoyer exige franchise, juste positionnement, respect et capacité à s’opposer fermement à ce qui dégrade le milieu commun."),
 T('clarte-et-verite','Clarté et vérité','central','direct',[18,20,22,23,24,25,27,28,30,31,36],"La réussite des œuvres dépend d’un langage clair et de relations qui ne s’abritent pas derrière des masques. Le psaume demande que le oui et le non soient reconnaissables et que les désaccords soient éclaircis jusqu’à ce que chacun retrouve une place juste."),
 T('fidelite-aux-engagements','Fidélité aux engagements','important','direct',[6,7,8,9,13,32,33,34],"La fidélité maintient la dignité, la noblesse et la continuité de l’œuvre. Le texte valorise ceux qui continuent à soutenir ce qu’ils ont choisi malgré les difficultés plutôt que ceux qui abandonnent à mesure que l’effort devient exigeant."),
 T('respect-des-autres','Respect des autres','important','direct',[16,17,18,21,22,31],"Respecter l’autre ne signifie pas éviter tout conflit mais ne pas détruire sa vie par regard, parole ou acte. Le texte reconnaît en chacun quelque chose de précieux et demande des relations où la fermeté reste ordonnée à la clarté et au Bien commun."),
 T('bien-commun','Bien commun','important','direct',[3,14,21,24,33,36,38],"L’œuvre individuelle doit être replacée dans une finalité collective. L’impersonnalité consiste à privilégier ce qui bénéficie à l’ensemble et aux générations futures sans nier les besoins particuliers mais sans en faire le centre."),
]},
151:{'signals':['purification','eau','hygiène subtile','conscience','corps d’immortalité'], 'themes':[
 T('purification-par-l-eau','Purification par l’eau','central','direct',[1,2,3,4,5,6,7,11,13,14,15,16,17,18,19,20,21,22,24,25,26,27],"L’eau est présentée comme une force de nettoyage, de régénération et d’enseignement qu’il faut reconnaître dans le corps physique comme dans les dimensions plus subtiles décrites par le texte. La purification devient un travail quotidien plutôt qu’une action exceptionnelle."),
 T('hygiene-du-corps-d-eau','Hygiène du corps d’eau','central','symbolic',[7,8,11,12,13,14,15,16,18,22,23,34],"L’hygiène ne concerne pas seulement la peau et le corps visible. Pensées, états d’âme et relations doivent eux aussi être régulièrement clarifiés afin d’éviter la stagnation et l’accumulation de ce que le psaume décrit comme des déchets psychiques."),
 T('eau-et-conscience','Eau et conscience','central','symbolic',[19,20,21,22,23,24,25,26,27],"L’eau sert de chemin vers la source de la conscience. Observation de soi, questionnement et attention à la pensée, aux sentiments et à la volonté doivent rendre ce courant plus clair et permettre une maîtrise plus consciente des actes."),
 T('purification-quotidienne','Purification quotidienne','important','direct',[13,14,15,17,23,25,34],"Le texte insiste sur la régularité : une bonne intention ou une pratique occasionnelle ne suffit pas à maintenir la clarté. Chaque jour doit comporter un travail de nettoyage, d’observation et de réorientation."),
 T('corps-de-purete-et-d-immortalite','Corps de pureté et d’immortalité','important','direct',[8,18,24,27,30,34],"La purification est reliée à la construction d’un autre corps capable de porter la pureté, la vérité et une continuité au-delà du corps physique. Les déchets et la stagnation sont présentés comme obstacles à cette formation."),
 T('trois-spheres','Trois sphères : pensée, sentiments, volonté','important','direct',[21,22,25,28,29,30,31,32,33,34],"L’action de l’eau est appliquée aux trois sphères de la pensée, des sentiments et de la volonté. Chacune doit retrouver clarté, équilibre et orientation afin que l’ensemble de la vie devienne cohérent."),
]},
152:{'signals':['source','continuité','âme','œuvre durable','unité'], 'themes':[
 T('source','Source','central','symbolic',[6,8,9,10,11,12,14,15,16,17,18,19,20,22,23,26,27,28],"La source symbolise une vie qui ne se laisse pas arrêter ni enfermer dans le point de vue individuel. Elle traverse les mondes, descend vers les profondeurs puis remonte, et invite l’homme à vivre comme partie d’un courant plus vaste plutôt qu’à vouloir le posséder."),
 T('continuite-de-la-vie','Continuité de la vie','central','direct',[9,10,11,12,13,19,20,22,28],"La vie est décrite comme continuité et perpétuité, tandis que la mort est assimilée à séparation et fixation. L’homme doit donc laisser des œuvres capables de continuer après son passage et participer à un mouvement qui ne s’arrête pas avec son individu."),
 T('oeuvre-qui-survit-a-l-individu','Œuvre qui survit à l’individu','central','direct',[9,11,12,13],"Rencontrer la source se vérifie par la capacité à créer quelque chose qui reste vivant au-delà de soi. Peu importe qui poursuit l’œuvre : le critère est la continuité de la vie et non la propriété personnelle de ce qui a été commencé."),
 T('impersonnalite-de-la-source','Impersonnalité de la source','important','direct',[1,2,3,4,6,14,15,16],"La source ne coule pas pour un seul être et ne se laisse pas réduire aux besoins du corps mortel. Le psaume demande de renoncer à vouloir tout ramener à soi afin d’entrer dans une vision plus large, impersonnelle et universelle."),
 T('eau-comme-ame','Eau comme âme','important','symbolic',[18,19,20,21,22,23,25],"L’eau est explicitement associée à l’âme et au voyage entre profondeur et hauteur. Elle relie les êtres et les règnes dans un mouvement de descente vers le centre puis de remontée vers une unité plus vaste."),
 T('tradition-comme-courant-vivant','Tradition comme courant vivant','important','symbolic',[24,26,27,28],"La Tradition est comparée à la source lorsqu’elle reste pure et en mouvement. Elle doit porter, purifier et construire un corps plutôt que devenir une forme figée qui bloque le passage du courant."),
]},
153:{'signals':['légèreté','eau du monde','âme','discernement','désencombrement'], 'themes':[
 T('legerete','Légèreté','central','direct',[5,13,14,15,16,17,18,20,21,22,23,28,31,34],"La légèreté est la clé proposée pour traverser le monde de l’eau sans être capturé par tout ce qui sollicite les sens et l’attention. Elle exige de ne pas accumuler inutilement informations, liens, charges et identifications qui alourdissent la vie."),
 T('traverser-l-eau-du-monde','Traverser l’eau du monde','central','symbolic',[1,2,3,4,5,8,9,10,11,12,16,28,29,30,34],"L’eau représente ici le monde de résonance qui amplifie ce que l’homme porte. Traverser cette eau signifie rester suffisamment formé, neutre et conscient pour ne pas être absorbé par les échos et influences qui apparaissent autour de lui."),
 T('discernement-des-solicitations','Discernement des sollicitations','central','direct',[10,11,12,15,17,18,19,21,22,23,31,33],"L’homme doit sélectionner ce qu’il regarde, écoute, goûte et accepte de porter. Tout ce qui attire son attention crée, dans la logique du psaume, un lien et un échange; le discernement protège donc l’espace intérieur contre les charges inutiles."),
 T('espace-vierge-et-neutre','Espace vierge et neutre','important','direct',[16,20,31,34,35],"Un espace intérieur neutre doit rester libre des sollicitations permanentes. Cette virginité permet d’approcher l’essentiel sans projeter immédiatement les concepts accumulés dans le monde humain."),
 T('faire-le-menage-dans-sa-vie','Faire le ménage dans sa vie','important','direct',[21,22,23,24,25,26,27,28,31,32,33],"Alléger la vie suppose de reconnaître que les liens entamés et les informations absorbées continuent à agir. Le texte demande donc de trier, fermer certaines associations et cesser d’offrir de l’énergie à ce qui ne participe pas au chemin choisi."),
 T('ame-et-autre-rive','Âme et autre rive','important','symbolic',[1,3,4,7,8,11,15,16,28],"L’autre rive symbolise la rencontre avec l’âme. Pour y parvenir, il faut un corps formé et assez léger pour ne pas être retenu par les multiples mondes qui se présentent lorsque l’eau amplifie les affinités accumulées."),
]}}
def merge(e,n):
 by={t.get('themeId'):t for t in e}; [by.__setitem__(t['themeId'],t) for t in n]; o={t['themeId']:i for i,t in enumerate(n)}
 return sorted(by.values(),key=lambda t:(0 if t.get('themeId') in o else 1,o.get(t.get('themeId'),999),t.get('themeId','')))
def main():
 d=json.loads(PATH.read_text(encoding='utf-8')); by={a['number']:a for a in d['psalmAnalyses']}
 for num,s in DEEP.items(): by[num].update({'titleSignals':s['signals'],'themes':merge(by[num].get('themes',[]),s['themes']),'semanticDepth':'deep-content-grounded'})
 d['psalmAnalyses']=sorted(by.values(),key=lambda a:a['number']); m=d.setdefault('method',{}); m['semanticPass']='deepening-in-progress'; m['deepPsalmCount']=sum(a.get('semanticDepth')=='deep-content-grounded' for a in d['psalmAnalyses']); PATH.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n',encoding='utf-8'); print(f"Book 22 deep total={m['deepPsalmCount']}")
if __name__=='__main__': main()
