#!/usr/bin/env python3
"""Third close semantic pass for Michael book 21, Psalms 140-143, PDF-derived only."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; PATH=ROOT/'data/thematic-index/books/book-21.json'
def T(i,l,imp,d,v,t): return {'themeId':i,'label':l,'importance':imp,'directness':d,'verseNumbers':v,'teaching':t}
DEEP={
140:{'signals':['parole vivante','discernement','corps de sagesse','transmission','Tradition'], 'themes':[
 T('parole-vivante','Parole vivante','central','direct',[1,2,3,5,6,7,9,10,14,15,16,19,20,22,25,28,29,30],"Le psaume oppose la répétition mécanique à une parole réellement portée par une intelligence et un corps. Une parole devient vivante lorsqu’elle est comprise, vérifiée, incarnée et reliée à une source que l’homme a appris à discerner."),
 T('discernement-de-la-parole','Discernement de la parole','central','direct',[4,5,9,14,15,20,23,25,26,28,29],"Avant de répéter ou transmettre ce qu’il entend, l’homme doit peser, vérifier et identifier l’intelligence qui anime la parole. Le critère proposé est moins l’apparence savante que la capacité de la parole à éclairer, relier et produire une vie cohérente."),
 T('corps-de-sagesse','Corps de sagesse','central','direct',[6,7,8,10,14,25,29,30],"Le texte insiste sur la nécessité de se former un corps avec la sagesse. Une connaissance seulement entendue reste sans consistance; elle devient transmissible lorsqu’elle est vécue, structurée et capable de produire des effets dans la vie."),
 T('transmission-vivante','Transmission vivante','important','direct',[10,15,16,17,20,22,30],"Transmettre ne consiste pas à répéter des mots mais à faire passer une vie. La Tradition reste vivante lorsque ceux qui la portent ont eux-mêmes rendu les paroles intelligentes, fécondes et capables d’ennoblir ceux qui les reçoivent."),
 T('apparence-de-savoir','Apparence de savoir','important','direct',[1,2,5,6,9,11,18,19,25,26],"Le psaume critique l’apparence de savoir produite par des mots empruntés, des jugements et des certitudes non vérifiées. Cette imitation de l’intelligence coupe progressivement l’homme de l’étude réelle et des mondes qu’il prétend représenter."),
 T('art-magique-de-la-parole','Art magique de la parole','important','symbolic',[15,16,20,22,23,28],"La parole est décrite comme un art capable d’ouvrir ou de fermer des portes entre les mondes. Son usage demande donc conscience, sensibilité et responsabilité afin que la parole soit au service de la communication et de l’harmonie plutôt que de l’enfermement."),
]},
141:{'signals':['confusion des mondes','ordre céleste','discernement','étude','juste place'], 'themes':[
 T('confusion-des-mondes','Confusion des mondes','central','direct',[4,5,6,7,8,12,14,20,21,22,24],"La confusion vient du mélange de réalités différentes et de l’incapacité à nommer ce qui appartient à chaque monde. Elle produit des jugements hâtifs, des usages déplacés de la Lumière et une perte de consistance dans la vie."),
 T('ordre-celeste','Ordre céleste','central','direct',[7,9,11,15,16,20,23],"L’ordre céleste correspond à la juste place de chaque manifestation dans un ensemble plus vaste. Le texte affirme que l’harmonie apparaît lorsque les différences sont reconnues sans être confondues ni réduites à un seul critère extérieur."),
 T('discernement-par-l-etude','Discernement par l’étude','central','direct',[2,3,7,17,19,21,25,26,27],"L’étude est la discipline qui permet de sortir des réactions automatiques et des sympathies ou antipathies. Elle apprend à prendre du recul, à considérer plusieurs mondes et à différer le jugement jusqu’à ce qu’une compréhension plus complète apparaisse."),
 T('dignite-de-chaque-monde','Dignité de chaque monde','important','direct',[9,10,11,15,16,20,23],"Chaque être et chaque règne possède une intégrité qui doit être respectée. La dignité consiste à ne pas dénaturer un monde en lui imposant une place ou une définition qui ne correspond pas à sa nature propre."),
 T('impersonnalite-de-l-etude','Impersonnalité de l’étude','important','direct',[25,26,27],"Entrer dans l’étude demande de laisser provisoirement à la porte les habitudes et intérêts personnels. Cet espace intérieur permet de regarder une situation autrement et de revenir ensuite dans la vie quotidienne avec une compréhension moins conditionnée."),
 T('simplicite-et-evidence','Simplicité et évidence','important','direct',[6,11,12,23],"La sagesse n’est pas associée ici à la complication mais à une évidence universelle où chaque chose est reconnue dans son monde. Les philosophies qui justifient le mélange sont au contraire décrites comme des constructions qui éloignent de cette simplicité."),
]},
142:{'signals':['réactivité','sagesse','plan global','passé-présent-futur','nouvelle éducation'], 'themes':[
 T('reactivite','Réactivité','central','direct',[1,2,3,4,5,9,11,18],"Le texte décrit l’homme réactif comme quelqu’un qui répond immédiatement aux événements avec des modèles déjà appris. Cette rapidité peut résoudre l’apparence d’un problème mais reproduit souvent les mêmes causes faute d’une vision plus profonde."),
 T('sagesse-comme-solution','Sagesse comme solution','central','direct',[4,5,6,7,8,10,11,15,16,19,20,21],"La sagesse cherche l’origine du problème, sa logique et son devenir plutôt qu’un simple soulagement immédiat. Elle conduit l’énergie vers une solution durable qui construit progressivement un corps d’intelligence."),
 T('passe-present-futur','Passé, présent et futur','central','direct',[16,17,19],"Toute situation doit être regardée à travers la continuité du passé, du présent et du devenir. Négliger l’un de ces trois temps condamne, selon le psaume, à répéter les mêmes erreurs et à subir une destinée non comprise."),
 T('nouvelle-education','Nouvelle éducation','important','direct',[3,9,10,12,13,14,15,22,23],"La nouvelle éducation vise à former des penseurs capables de comprendre les raisons d’un événement et de transmettre ensuite ce savoir. Elle doit devenir une culture quotidienne plutôt qu’une réaction ponctuelle face aux difficultés."),
 T('meditation-comme-capacite','Méditation comme capacité','important','direct',[10,19,20],"La méditation est définie comme un état clair, calme et entraîné qui permet de percevoir une situation dans son ensemble. Elle ne dispense pas d’agir mais prépare une action qui sait où elle veut conduire l’énergie."),
 T('transmission-du-savoir-faire','Transmission du savoir-faire','important','direct',[12,17,22,23],"Le savoir devient transmissible lorsqu’il a été acquis par un travail intérieur et une maîtrise réelle. Ce n’est qu’alors qu’il peut devenir une tradition vivante capable d’éduquer d’autres personnes et de modifier durablement un milieu collectif."),
]},
143:{'signals':['ensemencement de la terre','pensée créatrice','œuvre','Alliance','force collective'], 'themes':[
 T('ensemencement-de-la-terre','Ensemencement de la terre','central','symbolic',[1,4,5,6,7,10],"Le psaume présente les œuvres comme des semences déposées dans la terre pour l’avenir. Ensemencer signifie donner une forme durable à la sagesse afin que la vie et le lien avec le monde divin puissent continuer au-delà du présent."),
 T('pensee-creatrice','Pensée créatrice','central','direct',[1,2,3,4,7],"La pensée créatrice exige maîtrise intérieure et hauteur de vue. Le texte demande de ne pas prendre l’apparence visible pour toute la réalité mais de regarder les événements avec une intelligence capable d’en discerner la portée."),
 T('oeuvre-pour-l-avenir','Œuvre pour l’avenir','central','direct',[4,5,6,7,10,11],"L’œuvre est jugée par sa capacité à laisser une trace vivante et utile au futur. L’homme ne doit pas utiliser les dons uniquement pour sa satisfaction matérielle mais les conduire vers une réalisation qui maintient et développe la vie."),
 T('alliance-a-entretenir','Alliance à entretenir','important','direct',[6,8,9,10],"L’Alliance doit être régulièrement scellée et entretenue afin d’éviter le vide et la dispersion. Les célébrations et travaux mentionnés sont présentés comme des moyens concrets de maintenir un lien vivant entre les mondes."),
 T('force-collective','Force collective','important','direct',[9,10,11],"La réalisation finale demande d’unir et de concentrer les forces. Le texte relie prospérité, respect mutuel et capacité de chacun à trouver une place juste dans l’œuvre commune plutôt qu’à agir dans la dysharmonie."),
 T('discernement-des-apparences','Discernement des apparences','important','direct',[2,3],"La conscience doit s’élever au-dessus du seul point de vue physique afin de discerner ce qui se cache derrière les événements. Cette lecture évite de confondre une apparence immédiate avec la vérité entière d’une situation."),
]}}
def merge(e,n):
 by={t.get('themeId'):t for t in e}; [by.__setitem__(t['themeId'],t) for t in n]; o={t['themeId']:i for i,t in enumerate(n)}
 return sorted(by.values(),key=lambda t:(0 if t.get('themeId') in o else 1,o.get(t.get('themeId'),999),t.get('themeId','')))
def main():
 d=json.loads(PATH.read_text(encoding='utf-8')); by={a['number']:a for a in d['psalmAnalyses']}
 for num,s in DEEP.items(): by[num].update({'titleSignals':s['signals'],'themes':merge(by[num].get('themes',[]),s['themes']),'semanticDepth':'deep-content-grounded'})
 d['psalmAnalyses']=sorted(by.values(),key=lambda a:a['number']); m=d.setdefault('method',{}); m['semanticPass']='deepening-in-progress'; m['deepPsalmCount']=sum(a.get('semanticDepth')=='deep-content-grounded' for a in d['psalmAnalyses']); PATH.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n',encoding='utf-8'); print(f"Book 21 deep total={m['deepPsalmCount']}")
if __name__=='__main__': main()
