#!/usr/bin/env python3
"""First close semantic pass for Michael book 21, Psalms 131-135, PDF-derived only."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; PATH=ROOT/'data/thematic-index/books/book-21.json'
def T(i,l,imp,d,v,t): return {'themeId':i,'label':l,'importance':imp,'directness':d,'verseNumbers':v,'teaching':t}
DEEP={
131:{'signals':['vie réelle','simplicité','pureté','discernement','acte créateur'], 'themes':[
 T('vie-reelle','Vie réelle','central','direct',[1,2,3,4,5,7,12,13,15,16,17,18,19],"Michaël situe la vie dans ce qui est proche, concret et effectivement manifesté plutôt que dans la recherche de phénomènes extraordinaires. Chercher la Lumière demande ainsi d’apprendre à reconnaître la vie là où elle se donne déjà et à cesser de projeter sur elle ses propres constructions."),
 T('purete-des-mondes','Pureté des mondes','central','direct',[6,8,9,10,11,19],"La pureté consiste à ne pas mélanger les mondes ni à obliger la Lumière à prendre la forme des désirs humains. L’homme doit être identifié, préparé et formé dans chaque dimension de sa vie avant de prétendre s’unir à ce qu’il appelle supérieur."),
 T('discernement-mortel-immortel','Discernement mortel-immortel','central','direct',[7,12,13,14,15,16,18],"Le psaume oppose ce qui sert uniquement la vie mortelle à ce qui porte une semence de continuité. Le discernement doit s’acquérir par une formation vécue pas à pas et par l’observation de ce qui conduit vers la liberté, la sagesse et l’impersonnel."),
 T('acte-createur','Acte créateur','important','direct',[6,15,16,17,19],"Pensée, parole, geste et activité écrivent un monde devant l’homme. L’acte créateur juste est celui qui devient conscient, précis et cohérent avec l’intelligence que l’homme veut réellement incarner."),
 T('abstraction-et-illusion','Abstraction et illusion','important','direct',[2,3,5,12,16,17],"L’abstraction apparaît lorsqu’un homme cherche ailleurs un monde divin imaginé ou projette ses désirs sur la réalité. Le texte avertit que cette création subjective devient elle-même le monde dans lequel il finit par vivre."),
 T('service-de-la-lumiere','Service de la Lumière','important','direct',[7,10,11,18,19],"La Lumière n’est pas présentée comme une puissance à capturer au service d’un intérêt humain. Le mouvement demandé est inverse : modeler la vie et l’activité afin de servir ce qui est reconnu comme plus haut et bénéfique à plusieurs mondes."),
]},
132:{'signals':['pouvoir créateur','parole vivante','conscience','Tradition','pensée-parole-acte'], 'themes':[
 T('pouvoir-createur','Pouvoir créateur','central','direct',[1,2,3,4,10,16,17,18,21,24,25],"Le pouvoir créateur de l’homme agit même lorsqu’il n’en est pas conscient. Reprendre ce pouvoir signifie identifier l’intelligence à laquelle pensées, paroles et actes sont associés puis les orienter consciemment au lieu de servir des mondes inconnus."),
 T('parole-vivante','Parole vivante','central','direct',[3,5,6,7,8,9,10,11,12,13,14,15,16,17,18,21,22,24,25],"La parole est décrite comme un organe créateur qui relie plusieurs mondes. Elle perd sa fonction lorsqu’elle devient simple bruit ou expression d’impulsions; elle la retrouve lorsqu’une pensée, une âme, une intelligence et un acte lui donnent un corps cohérent."),
 T('pensee-parole-acte','Pensée, parole et acte','central','direct',[10,12,14,15,17,18,21,24],"La vérité créatrice exige une continuité entre ce qui est pensé, dit et accompli. Une parole sans acte reste sans consistance, tandis qu’un acte conscient donne un corps à l’intelligence portée dans les mots."),
 T('education-de-la-parole','Éducation de la parole','important','direct',[4,9,13,21,24],"L’éducation doit réapprendre à parler avec précision et conscience. Le texte demande d’écouter ses propres mots, de comprendre leur sens réel et d’observer le monde qu’ils révèlent et construisent."),
 T('tradition-comme-trait-d-union','Tradition comme trait d’union','important','direct',[18,19,20,22,23],"La Tradition est présentée comme le milieu qui reconnecte pensée, parole et acte à une intelligence plus vaste. Elle offre un langage transmis où l’homme peut réapprendre à inscrire sa vie dans une filiation consciente plutôt que dans l’inconscience."),
 T('alliances-creatrices','Alliances créatrices','important','direct',[15,16,17,18,22,23],"Créer n’est jamais un acte isolé : les associations invisibles donnent leur orientation à la pensée, à la parole et à l’action. Le travail consiste donc à choisir avec quelles intelligences et quels principes l’homme accepte de construire."),
]},
133:{'signals':['éducation','ordre des mondes','responsabilité','dettes','travail sur soi'], 'themes':[
 T('education-essenienne','Éducation essénienne','central','direct',[1,2,3,6,12,14,17,18,20,21],"L’éducation proposée vise à remettre en ordre les différentes dimensions de l’homme plutôt qu’à favoriser soit le rejet du monde physique, soit le rejet de l’esprit. Elle apprend à identifier les mondes, à les séparer lorsqu’ils sont confondus et à leur donner une juste place."),
 T('ordre-des-mondes','Ordre des mondes','central','direct',[2,3,4,5,6,14,17,21],"L’homme est comparé à un ensemble de pièces mal assemblées. La clarté vient lorsqu’il harmonise pensée, sentiment, volonté, monde physique et monde invisible au lieu de les mélanger dans des aspirations contradictoires."),
 T('responsabilite-de-sa-destinee','Responsabilité de sa destinée','central','direct',[6,7,8,9,10,12,13,15,16,20,21],"Le texte refuse l’idée que le monde divin doive effacer les conséquences des choix humains. Reprendre sa destinée en mains signifie assumer ses associations, poser des actes concrets de clarification et construire progressivement une autre direction."),
 T('dettes-et-associations','Dettes et associations','important','direct',[7,12,13],"Les dettes figurent les conséquences d’associations et de pactes antérieurs. Se tourner vers un idéal nouveau ne les annule pas : elles doivent être reconnues puis travaillées par l’étude, l’éveil et des actes qui modifient réellement la vie."),
 T('travail-sur-soi','Travail sur soi','important','direct',[8,9,10,12,14,20,21],"Le travail sur soi est la condition pour que l’aspiration à la Lumière cesse d’être une demande d’assistance extérieure. Il passe par l’étude, l’organisation, la construction d’un corps et la création d’un espace intérieur clair."),
 T('purete-comme-separation','Pureté comme séparation','important','direct',[11,17,18,21],"La pureté est décrite comme capacité à empêcher le mélange et la confusion d’entrer dans un espace destiné à la Lumière. Elle exige une formation réelle plutôt qu’une simple intention ou quelques paroles de sagesse."),
]},
134:{'signals':['travail','activité créatrice','Bien commun','Alliance','transmission'], 'themes':[
 T('sceau-du-travail','Sceau du Travail','central','direct',[4,12,14,18,19,21,23,25,26],"Le sceau du Travail sert à réinterroger le sens de l’activité humaine. Travailler ne doit pas seulement assurer la vie matérielle : l’activité peut aussi devenir le lieu où une intelligence, une âme et une finalité plus vastes prennent corps."),
 T('activite-creatrice','Activité créatrice','central','direct',[3,8,11,12,13,14,15,16,17,18,19,20,21,22,27,28,29],"Toute activité mobilise des énergies et construit un monde. Le psaume demande donc d’identifier pour qui et pour quoi l’on agit, puis de conduire le travail vers un résultat conscient plutôt que de confondre agitation et réalisation."),
 T('alliance-dans-l-oeuvre','Alliance dans l’œuvre','central','direct',[6,7,17,19,20,22,23,24,25,26,28],"Une œuvre durable suppose un accord entre plusieurs règnes, intelligences et communautés. L’Alliance est le cadre où l’activité individuelle devient un travail partagé pouvant être transmis au-delà de l’intérêt personnel."),
 T('bien-commun','Bien commun','important','direct',[6,19,23,25,26],"Le Bien commun sert de critère pour élargir l’activité au-delà du seul bénéfice humain. Une œuvre juste doit pouvoir trouver une place dans plusieurs règnes et être examinée depuis les intérêts de l’ensemble auquel elle participe."),
 T('transmission-des-oeuvres','Transmission des œuvres','important','direct',[1,5,8,24,27,28],"Le travail prend une portée durable lorsqu’une pensée et un savoir-faire peuvent être transmis. Le psaume insiste sur la préparation d’un futur et sur la loi selon laquelle ce qui est correctement posé en petit peut ensuite apparaître en grand."),
 T('conscience-des-finalites','Conscience des finalités','important','direct',[5,16,18,19,21],"La conscience permet de dévoiler l’intelligence et le but cachés derrière l’activité. Elle distingue un travail centré sur la survie ou la réussite personnelle d’une œuvre qui cherche à devenir support d’une intelligence plus universelle."),
]},
135:{'signals':['dignité','royauté intérieure','deux mondes','valeur','transmission'], 'themes':[
 T('dignite','Dignité','central','direct',[1,2,3,4,8,11,13,14,17,18,19,20],"La dignité est définie comme une force intérieure capable de donner de la valeur aux êtres, aux pensées, aux sentiments et aux actes. Elle ne dépend pas d’un rang matériel mais de la capacité à rester noble et conscient dans les deux dimensions visible et invisible de la vie."),
 T('royaut-e-interieure','Royauté intérieure','central','direct',[1,3,11,13,14,20],"La royauté intérieure apparaît lorsque l’homme cesse d’abdiquer son jugement devant les influences et reprend la direction de sa pensée, de ses sentiments et de ses actes. Être royal signifie ici ennoblir ce qui est rencontré plutôt que dominer."),
 T('discernement-des-influences','Discernement des influences','central','direct',[2,3,4,5,8,9,10,15,16,21],"Le psaume décrit l’homme comme traversé par des mondes invisibles qu’il confond avec lui-même. Le discernement consiste à reconnaître ces influences, à prendre du recul et à choisir lesquelles peuvent réellement orienter la vie."),
 T('deux-mondes','Deux mondes','important','direct',[3,4,5,6,20,21],"La grandeur exige d’être éveillé à la fois dans le visible et l’invisible. Le texte rejette aussi bien l’asservissement à la matière que l’usage du spirituel pour dominer le monde physique : les deux doivent être équilibrés."),
 T('valeur-et-noblesse','Valeur et noblesse','important','direct',[4,8,11,13,14,17,18,19],"La valeur est ce qui peut être vécu, incarné et transmis : paroles de sagesse, sentiments qui guérissent, vertus, convictions et engagements. Les apparences et possessions qui n’expriment aucune vie intérieure sont décrites comme temporaires."),
 T('transmission-vivante','Transmission vivante','important','direct',[16,17,18,19],"Ce qui perdure est ce qui peut être transmis dans une Tradition vivante. Une valeur conduite dans des actes et des œuvres peut continuer dans d’autres êtres et générations, tandis que ce qui n’a pas été incarné s’éteint."),
]}}
def merge(e,n):
 by={t.get('themeId'):t for t in e}; [by.__setitem__(t['themeId'],t) for t in n]; o={t['themeId']:i for i,t in enumerate(n)}
 return sorted(by.values(),key=lambda t:(0 if t.get('themeId') in o else 1,o.get(t.get('themeId'),999),t.get('themeId','')))
def main():
 d=json.loads(PATH.read_text(encoding='utf-8')); by={a['number']:a for a in d['psalmAnalyses']}
 for num,s in DEEP.items(): by[num].update({'titleSignals':s['signals'],'themes':merge(by[num].get('themes',[]),s['themes']),'semanticDepth':'deep-content-grounded'})
 d['psalmAnalyses']=sorted(by.values(),key=lambda a:a['number']); m=d.setdefault('method',{}); m['semanticPass']='deepening-in-progress'; m['deepPsalmCount']=sum(a.get('semanticDepth')=='deep-content-grounded' for a in d['psalmAnalyses']); PATH.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n',encoding='utf-8'); print(f"Book 21 deep total={m['deepPsalmCount']}")
if __name__=='__main__': main()
